# -*- coding: utf-8 -*-
"""Soczyste rabaty.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bfU5lwdNa2GOPWmQ9-URaf30VnlBzQC0
"""

#importowanie potrzebnych bibliotek
import os
import openpyxl
import streamlit as st
import pandas as pd
import numpy as np
import altair as alt
import plotly.express as px
import plotly.graph_objects as go
from urllib.request import urlopen
import json
import io
import datetime
import re




st.set_page_config(page_title='Monitoringi AUTOMATY', layout='wide')


sekcja = st.sidebar.radio(
    'Wybierz monitoring:',
    ('Oferta sezonowa', 'Standy wrzesień-marzec','Vit D','Zioła mix')
 )

tabs_font_css = """
<style>
div[class*="stTextInput"] label {
  font-size: 26px;
  color: black;
}
div[class*="stSelectbox"] label {
  font-size: 26px;
  color: black;
}
</style>
"""
#POTRZEBNE FUNKCJE
#1 Funkcja do wyodrębnienia wartości procentowej
def extract_percentage(text):
    import re
    match = re.search(r'(\d+,\d+|\d+)%', text)
    return match.group(0) if match else ''

#2 Funkcja do konwersji wartości procentowej na float
def percentage_to_float(percentage_str):
    if pd.isna(percentage_str) or not percentage_str:
        return 0.0  # Zmieniono na 0.0, aby brakujące wartości były traktowane jako 0
    # Zamiana przecinka na kropkę, usunięcie znaku '%'
    return float(percentage_str.replace(',', '.').replace('%', ''))

def extract_numbers_as_text(text):
    numbers = re.findall(r'\d+', text)
    return f"{numbers[0]}+{numbers[1]}" if len(numbers) >= 2 else None


dzisiejsza_data = datetime.datetime.now().strftime("%d.%m.%Y")


############################################################################### Zioła mix  ##############################################################################################
if sekcja == 'Zioła mix':
    st.write(tabs_font_css, unsafe_allow_html=True)

    df = st.file_uploader(
    label = "Wrzuć plik - Zioła mix"
    )
    if df:
        df = pd.read_excel(df, sheet_name = 'Rabat', skiprows = 11, usecols = [1,3,9])
        st.write(df.head())
        
        #usuń braki danych z Kod klienta
    df = df.dropna(subset=['Kod SAP'])

    # klient na całkowite
    df = df[df['Klient'] != '(puste)']
    df['Klient'] = df['Klient'].astype(int)
    df['Kod SAP'] = df['Kod SAP'].astype(int)

    # Zmiana nazw kolumn
    #df = df.rename(columns={'0.12.1': '12', '0.14.1': '14'})

    #Dodaj kolumnę 'SIECIOWY', która będzie zawierać 'SIECIOWY' jeśli w kolumnach '12' lub '14' jest słowo 'powiązanie'
    df['SIECIOWY'] = df.apply(lambda row: 'SIECIOWY' if 'powiązanie' in str(row['Pakiet']).lower() else '', axis=1)

    #SPRAWDZENIE CZY DZIAŁA
    df[df['SIECIOWY'] == 'SIECIOWY']
    #DZIAŁA :)

    
    # Zastosowanie funkcji do kolumn '12' i '14'
    df['Pakiet'] = df['Pakiet'].apply(extract_percentage)
    #df['14_percent'] = df['14'].apply(extract_percentage)


    # Konwersja kolumn '12_percent' i '14_percent' na liczby zmiennoprzecinkowe
    df['Pakiet'] = df['Pakiet'].apply(percentage_to_float)
    #df['14_percent'] = df['14_percent'].apply(percentage_to_float)

    # Dodaj nową kolumnę 'max_percent' z maksymalnymi wartościami z kolumn '12_percent' i '14_percent'
    df['max_percent'] = df[['Pakiet']].max(axis=1)

    # Wybierz wiersze, gdzie 'max_percent' nie jest równa 0
    filtered_df = df[df['max_percent'] != 0]
    filtered_df = df[df['max_percent'] == 15]

    standard = filtered_df[filtered_df['SIECIOWY'] != 'SIECIOWY']
    powiazanie = filtered_df[filtered_df['SIECIOWY'] == 'SIECIOWY']

    #len(standard), len(powiazanie), len(filtered_df)

    standard_ost = standard[['Kod SAP', 'max_percent']]

    powiazanie = powiazanie[['Klient','Kod SAP','max_percent']]


    #TERAZ IMS
    ims = st.file_uploader(
        label = "Wrzuć plik ims_nhd"
    )

    if ims:
        ims = pd.read_excel(ims, usecols=[0,2,19,21])
        st.write(ims.head())

    ims = ims[ims['APD_Czy_istnieje_na_rynku']==1]
    ims = ims[ims['APD_Rodzaj_farmaceutyczny'].isin(['AP - Apteka','ME - Sklep zielarsko - medyczny','PU - Punkt apteczny'])]

    wynik_df = pd.merge(powiazanie, ims, left_on='Klient', right_on='Klient', how='left')

    #Wybór potrzebnych kolumn: 'APD_kod_SAP_apteki' i 'max_percent'
    wynik_df = wynik_df[['Klient','APD_kod_SAP_apteki', 'max_percent']]


    #to są kody SAP
    wynik_df1 = wynik_df.rename(columns={'APD_kod_SAP_apteki': 'Kod SAP'})
    wynik_df1 = wynik_df1[['Kod SAP','max_percent']]
    #wynik_df1

    #to są kody powiazan
    wynik_df2 = wynik_df.rename(columns={'Klient': 'Kod SAP'})
    wynik_df2 = wynik_df2[['Kod SAP','max_percent']]
    #wynik_df2

    #POŁĄCZYĆ wynik_df z standard_ost
    polaczone = pd.concat([standard_ost, wynik_df1, wynik_df2], axis = 0)
  
    posortowane = polaczone.sort_values(by='max_percent', ascending=False)

    ostatecznie = posortowane.drop_duplicates(subset='Kod SAP')


    st.write('Jeśli to pierwszy monitoring, pobierz ten plik, jeśli nie, wrzuć plik z poprzedniego monitoringu i NIE POBIERAJ TEGO PLIKU')
    excel_file = io.BytesIO()
    with pd.ExcelWriter(excel_file, engine='xlsxwriter') as writer:
        ostatecznie.to_excel(writer, index=False, sheet_name='Sheet1')
    excel_file.seek(0)  # Resetowanie wskaźnika do początku pliku

    # Umożliwienie pobrania pliku Excel
    st.download_button(
        label='Pobierz, jeśli to pierwszy monitoring',
        data=excel_file,
        file_name='czy_dodac.xlsx',
        mime='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
    )

    #plik z poprzedniego monitoringu
    poprzedni = st.file_uploader(
        label = "Wrzuć plik z poprzedniego monitoringu"
    )

    if poprzedni:
        poprzedni = pd.read_excel(poprzedni)
        st.write(poprzedni.head())

    poprzedni = poprzedni.rename(columns={'max_percent': 'old_percent'})
    # Wykonanie left join, dodanie 'old_percent' do pliku 'ostatecznie'
    result = ostatecznie.merge(poprzedni[['Kod SAP', 'old_percent']], on='Kod SAP', how='left')
    result['old_percent'] = result['old_percent'].fillna(0)
    result['Czy dodać'] = result.apply(lambda row: 'DODAJ' if row['max_percent'] > row['old_percent'] else '', axis=1)
    st.write('Kliknij aby pobrać plik z kodami, które kody należy dodać')

    excel_file1 = io.BytesIO()
    with pd.ExcelWriter(excel_file1, engine='xlsxwriter') as writer:
        result.to_excel(writer, index=False, sheet_name='Sheet1')
    excel_file1.seek(0)  # Resetowanie wskaźnika do początku pliku

    nazwa_pliku1 = f"Zioła_mix_{dzisiejsza_data}.xlsx"
    #Umożliwienie pobrania pliku Excel
    st.download_button(
        label='Pobierz',
        data=excel_file1,
        file_name=nazwa_pliku1,
        mime='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
    )

    result = result.drop(columns=['old_percent', 'Czy dodać'])


    st.write('Kliknij, aby pobrać plik z formułą max do następnego monitoringu')
    excel_file2 = io.BytesIO()
    with pd.ExcelWriter(excel_file2, engine='xlsxwriter') as writer:
        result.to_excel(writer, index=False, sheet_name='Sheet1')
    excel_file1.seek(0)  # Resetowanie wskaźnika do początku pliku

    nazwa_pliku = f"FM_Zioła_mix_{dzisiejsza_data}.xlsx"
    # Umożliwienie pobrania pliku Excel
    st.download_button(
        label='Pobierz nowy plik FORMUŁA MAX',
        data=excel_file2,
        file_name = nazwa_pliku,
        mime='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
    )


############################################################################### OFERTA SEZONOWA  ##############################################################################################
if sekcja == 'Oferta sezonowa':
    st.write(tabs_font_css, unsafe_allow_html=True)

    df = st.file_uploader(
    label = "Wrzuć plik - Oferta sezonowa"
    )
    if df:
        df = pd.read_excel(df, sheet_name = 'Rabat', skiprows = 12, usecols = [1,3,8])
        st.write(df.head())
        
        #usuń braki danych z Kod klienta
    df = df.dropna(subset=['Kod SAP'])

    # klient na całkowite
    df = df[df['Klient'] != '(puste)']
    df['Klient'] = df['Klient'].astype(int)
    df['Kod SAP'] = df['Kod SAP'].astype(int)

    # Zmiana nazw kolumn
    #df = df.rename(columns={'0.12.1': '12', '0.14.1': '14'})

    #Dodaj kolumnę 'SIECIOWY', która będzie zawierać 'SIECIOWY' jeśli w kolumnach '12' lub '14' jest słowo 'powiązanie'
    df['SIECIOWY'] = df.apply(lambda row: 'SIECIOWY' if 'powiązanie' in str(row['Pakiet']).lower() else '', axis=1)

    #SPRAWDZENIE CZY DZIAŁA
    df[df['SIECIOWY'] == 'SIECIOWY']
    #DZIAŁA :)

    
    # Zastosowanie funkcji do kolumn '12' i '14'
    df['Pakiet'] = df['Pakiet'].apply(extract_percentage)
    #df['14_percent'] = df['14'].apply(extract_percentage)


    # Konwersja kolumn '12_percent' i '14_percent' na liczby zmiennoprzecinkowe
    df['Pakiet'] = df['Pakiet'].apply(percentage_to_float)
    #df['14_percent'] = df['14_percent'].apply(percentage_to_float)

    # Dodaj nową kolumnę 'max_percent' z maksymalnymi wartościami z kolumn '12_percent' i '14_percent'
    df['max_percent'] = df[['Pakiet']].max(axis=1)

    # Wybierz wiersze, gdzie 'max_percent' nie jest równa 0
    filtered_df = df[df['max_percent'] != 0]

    standard = filtered_df[filtered_df['SIECIOWY'] != 'SIECIOWY']
    powiazanie = filtered_df[filtered_df['SIECIOWY'] == 'SIECIOWY']

    #len(standard), len(powiazanie), len(filtered_df)

    standard_ost = standard[['Kod SAP', 'max_percent']]

    powiazanie = powiazanie[['Klient','Kod SAP','max_percent']]


    #TERAZ IMS
    ims = st.file_uploader(
        label = "Wrzuć plik ims_nhd"
    )

    if ims:
        ims = pd.read_excel(ims, usecols=[0,2,19,21])
        st.write(ims.head())

    ims = ims[ims['APD_Czy_istnieje_na_rynku']==1]
    ims = ims[ims['APD_Rodzaj_farmaceutyczny'].isin(['AP - Apteka','ME - Sklep zielarsko - medyczny','PU - Punkt apteczny'])]

    wynik_df = pd.merge(powiazanie, ims, left_on='Klient', right_on='Klient', how='left')

    #Wybór potrzebnych kolumn: 'APD_kod_SAP_apteki' i 'max_percent'
    wynik_df = wynik_df[['Klient','APD_kod_SAP_apteki', 'max_percent']]


    #to są kody SAP
    wynik_df1 = wynik_df.rename(columns={'APD_kod_SAP_apteki': 'Kod SAP'})
    wynik_df1 = wynik_df1[['Kod SAP','max_percent']]
    #wynik_df1

    #to są kody powiazan
    wynik_df2 = wynik_df.rename(columns={'Klient': 'Kod SAP'})
    wynik_df2 = wynik_df2[['Kod SAP','max_percent']]
    #wynik_df2

    #POŁĄCZYĆ wynik_df z standard_ost
    polaczone = pd.concat([standard_ost, wynik_df1, wynik_df2], axis = 0)
  
    posortowane = polaczone.sort_values(by='max_percent', ascending=False)

    ostatecznie = posortowane.drop_duplicates(subset='Kod SAP')


    st.write('Jeśli to pierwszy monitoring, pobierz ten plik, jeśli nie, wrzuć plik z poprzedniego monitoringu i NIE POBIERAJ TEGO PLIKU')
    excel_file = io.BytesIO()
    with pd.ExcelWriter(excel_file, engine='xlsxwriter') as writer:
        ostatecznie.to_excel(writer, index=False, sheet_name='Sheet1')
    excel_file.seek(0)  # Resetowanie wskaźnika do początku pliku

    # Umożliwienie pobrania pliku Excel
    st.download_button(
        label='Pobierz, jeśli to pierwszy monitoring',
        data=excel_file,
        file_name='czy_dodac.xlsx',
        mime='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
    )

    #plik z poprzedniego monitoringu
    poprzedni = st.file_uploader(
        label = "Wrzuć plik z poprzedniego monitoringu"
    )

    if poprzedni:
        poprzedni = pd.read_excel(poprzedni)
        st.write(poprzedni.head())

    poprzedni = poprzedni.rename(columns={'max_percent': 'old_percent'})
    # Wykonanie left join, dodanie 'old_percent' do pliku 'ostatecznie'
    result = ostatecznie.merge(poprzedni[['Kod SAP', 'old_percent']], on='Kod SAP', how='left')
    result['old_percent'] = result['old_percent'].fillna(0)
    result['Czy dodać'] = result.apply(lambda row: 'DODAJ' if row['max_percent'] > row['old_percent'] else '', axis=1)
    st.write('Kliknij aby pobrać plik z kodami, które kody należy dodać')

    excel_file1 = io.BytesIO()
    with pd.ExcelWriter(excel_file1, engine='xlsxwriter') as writer:
        result.to_excel(writer, index=False, sheet_name='Sheet1')
    excel_file1.seek(0)  # Resetowanie wskaźnika do początku pliku

    nazwa_pliku1 = f"Oferta_sezonowa_{dzisiejsza_data}.xlsx"
    #Umożliwienie pobrania pliku Excel
    st.download_button(
        label='Pobierz',
        data=excel_file1,
        file_name=nazwa_pliku1,
        mime='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
    )

    result = result.drop(columns=['old_percent', 'Czy dodać'])


    st.write('Kliknij, aby pobrać plik z formułą max do następnego monitoringu')
    excel_file2 = io.BytesIO()
    with pd.ExcelWriter(excel_file2, engine='xlsxwriter') as writer:
        result.to_excel(writer, index=False, sheet_name='Sheet1')
    excel_file1.seek(0)  # Resetowanie wskaźnika do początku pliku

    nazwa_pliku = f"FM_Oferta_sezonowa_{dzisiejsza_data}.xlsx"
    # Umożliwienie pobrania pliku Excel
    st.download_button(
        label='Pobierz nowy plik FORMUŁA MAX',
        data=excel_file2,
        file_name = nazwa_pliku,
        mime='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
    )




############################################################################# Standy wrzesień-marzec################################################################
if sekcja == 'Standy wrzesień-marzec':
    st.write(tabs_font_css, unsafe_allow_html=True)

    df = st.file_uploader(
    label = "Wrzuć plik - Standy wrzesień-marzec"
    )
    if df:
        df = pd.read_excel(df, sheet_name = 'Rabat', skiprows = 10, usecols = [1,3,9])
        st.write(df.head())
        
        #usuń braki danych z Kod klienta
    df = df.dropna(subset=['Kod SAP'])

    # klient na całkowite
    df = df[df['Klient'] != '(puste)']
    df['Klient'] = df['Klient'].astype(int)
    df['Kod SAP'] = df['Kod SAP'].astype(int)

    # Zmiana nazw kolumn
    #df = df.rename(columns={'0.12.1': '12', '0.14.1': '14'})

    #Dodaj kolumnę 'SIECIOWY', która będzie zawierać 'SIECIOWY' jeśli w kolumnach '12' lub '14' jest słowo 'powiązanie'
    df['SIECIOWY'] = df.apply(lambda row: 'SIECIOWY' if 'powiązanie' in str(row['Pakiet']).lower() else '', axis=1)

    #SPRAWDZENIE CZY DZIAŁA
    df[df['SIECIOWY'] == 'SIECIOWY']
    #DZIAŁA :)

    
    # Zastosowanie funkcji do kolumn '12' i '14'
    df['Pakiet'] = df['Pakiet'].apply(extract_percentage)
    #df['14_percent'] = df['14'].apply(extract_percentage)


    # Konwersja kolumn '12_percent' i '14_percent' na liczby zmiennoprzecinkowe
    df['Pakiet'] = df['Pakiet'].apply(percentage_to_float)
    #df['14_percent'] = df['14_percent'].apply(percentage_to_float)

    # Dodaj nową kolumnę 'max_percent' z maksymalnymi wartościami z kolumn '12_percent' i '14_percent'
    df['max_percent'] = df[['Pakiet']].max(axis=1)

    # Wybierz wiersze, gdzie 'max_percent' nie jest równa 0
    filtered_df = df[df['max_percent'] != 0]

    standard = filtered_df[filtered_df['SIECIOWY'] != 'SIECIOWY']
    powiazanie = filtered_df[filtered_df['SIECIOWY'] == 'SIECIOWY']

    #len(standard), len(powiazanie), len(filtered_df)

    standard_ost = standard[['Kod SAP', 'max_percent']]

    powiazanie = powiazanie[['Klient','Kod SAP','max_percent']]


    #TERAZ IMS
    ims = st.file_uploader(
        label = "Wrzuć plik ims_nhd"
    )

    if ims:
        ims = pd.read_excel(ims, usecols=[0,2,19,21])
        st.write(ims.head())

    ims = ims[ims['APD_Czy_istnieje_na_rynku']==1]
    ims = ims[ims['APD_Rodzaj_farmaceutyczny'].isin(['AP - Apteka','ME - Sklep zielarsko - medyczny','PU - Punkt apteczny'])]

    wynik_df = pd.merge(powiazanie, ims, left_on='Klient', right_on='Klient', how='left')

    #Wybór potrzebnych kolumn: 'APD_kod_SAP_apteki' i 'max_percent'
    wynik_df = wynik_df[['Klient','APD_kod_SAP_apteki', 'max_percent']]


    #to są kody SAP
    wynik_df1 = wynik_df.rename(columns={'APD_kod_SAP_apteki': 'Kod SAP'})
    wynik_df1 = wynik_df1[['Kod SAP','max_percent']]
    #wynik_df1

    #to są kody powiazan
    wynik_df2 = wynik_df.rename(columns={'Klient': 'Kod SAP'})
    wynik_df2 = wynik_df2[['Kod SAP','max_percent']]
    #wynik_df2

    #POŁĄCZYĆ wynik_df z standard_ost
    polaczone = pd.concat([standard_ost, wynik_df1, wynik_df2], axis = 0)
  
    posortowane = polaczone.sort_values(by='max_percent', ascending=False)

    ostatecznie = posortowane.drop_duplicates(subset='Kod SAP')


    st.write('Jeśli to pierwszy monitoring, pobierz ten plik, jeśli nie, wrzuć plik z poprzedniego monitoringu i NIE POBIERAJ TEGO PLIKU')
    excel_file = io.BytesIO()
    with pd.ExcelWriter(excel_file, engine='xlsxwriter') as writer:
        ostatecznie.to_excel(writer, index=False, sheet_name='Sheet1')
    excel_file.seek(0)  # Resetowanie wskaźnika do początku pliku

    # Umożliwienie pobrania pliku Excel
    st.download_button(
        label='Pobierz, jeśli to pierwszy monitoring',
        data=excel_file,
        file_name='czy_dodac.xlsx',
        mime='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
    )

    #plik z poprzedniego monitoringu
    poprzedni = st.file_uploader(
        label = "Wrzuć plik z poprzedniego monitoringu"
    )

    if poprzedni:
        poprzedni = pd.read_excel(poprzedni)
        st.write(poprzedni.head())

    poprzedni = poprzedni.rename(columns={'max_percent': 'old_percent'})
    # Wykonanie left join, dodanie 'old_percent' do pliku 'ostatecznie'
    result = ostatecznie.merge(poprzedni[['Kod SAP', 'old_percent']], on='Kod SAP', how='left')
    result['old_percent'] = result['old_percent'].fillna(0)
    result['Czy dodać'] = result.apply(lambda row: 'DODAJ' if row['max_percent'] > row['old_percent'] else '', axis=1)
    st.write('Kliknij aby pobrać plik z kodami, które kody należy dodać')

    excel_file1 = io.BytesIO()
    with pd.ExcelWriter(excel_file1, engine='xlsxwriter') as writer:
        result.to_excel(writer, index=False, sheet_name='Sheet1')
    excel_file1.seek(0)  # Resetowanie wskaźnika do początku pliku

    nazwa_pliku1 = f"Standy_wrzesień-marzec_{dzisiejsza_data}.xlsx"
    #Umożliwienie pobrania pliku Excel
    st.download_button(
        label='Pobierz',
        data=excel_file1,
        file_name=nazwa_pliku1,
        mime='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
    )

    result = result.drop(columns=['old_percent', 'Czy dodać'])


    st.write('Kliknij, aby pobrać plik z formułą max do następnego monitoringu')
    excel_file2 = io.BytesIO()
    with pd.ExcelWriter(excel_file2, engine='xlsxwriter') as writer:
        result.to_excel(writer, index=False, sheet_name='Sheet1')
    excel_file1.seek(0)  # Resetowanie wskaźnika do początku pliku

    nazwa_pliku = f"FM_Standy_wrzesień-marzec_{dzisiejsza_data}.xlsx"
    # Umożliwienie pobrania pliku Excel
    st.download_button(
        label='Pobierz nowy plik FORMUŁA MAX',
        data=excel_file2,
        file_name = nazwa_pliku,
        mime='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
    )



############################################################################### VIT D ##############################################################################################
if sekcja == 'Vit D':
    st.write(tabs_font_css, unsafe_allow_html=True)

    df = st.file_uploader(label="Wrzuć plik - Vit D")
    
    if df:
        xls = pd.ExcelFile(df)

        # 1. Odczyt arkuszy
        Lr = pd.DataFrame()
        Lg = pd.DataFrame()

        if 'Rabat' in xls.sheet_names:
            Lr = pd.read_excel(df, sheet_name='Rabat', skiprows=12, usecols=[1, 6])
            st.write("Dane z arkusza Rabat:")
            st.write(Lr.head())

        if 'Pakiet od 02.07' in xls.sheet_names:
            Lg = pd.read_excel(df, sheet_name='Pakiet od 02.07', skiprows=12, usecols=[1, 6])
            st.write("Dane z arkusza Pakiet od 02.07:")
            st.write(Lg.head())

        # --- CZYSZCZENIE I PRZYGOTOWANIE DANYCH ---
        if not Lr.empty:
            Lr.columns = ['Klient', 'Pakiet']
            Lr = Lr.dropna(subset=['Pakiet', 'Klient'])
            Lr = Lr[Lr['Klient'] != '(puste)']
            
            # Formatujemy Klienta jako tekst bez .0
            Lr['Klient'] = Lr['Klient'].astype(str).str.replace(r'\.0$', '', regex=True).str.strip()

            # Identyfikacja sieciowych
            Lr['SIECIOWY'] = Lr.apply(lambda row: 'SIECIOWY' if 'powiązanie' in str(row['Pakiet']).lower() else '', axis=1)
            
            # Ekstrakcja i konwersja wartości procentowych
            Lr['Pakiet'] = Lr['Pakiet'].apply(extract_percentage)
            Lr['Pakiet'] = Lr['Pakiet'].apply(percentage_to_float)
            
            # Zostawiamy rabaty równe lub większe od 20%
            Lr = Lr[Lr['Pakiet'] >= 20]

            # Dynamiczne generowanie grupy promocyjnej
            Lr['Grupa promocyjna'] = Lr['Pakiet'].apply(lambda x: f"VIT_D3_MAX_{int(x)}")

            # Wyznaczenie max_percent dla sieciowych i indywidualnych
            Lr1 = Lr[Lr['SIECIOWY'] == 'SIECIOWY'].copy()
            Lr2 = Lr[Lr['SIECIOWY'] != 'SIECIOWY'].copy()
            Lr1['max_percent'] = Lr1['Pakiet']
            Lr2['max_percent'] = Lr2['Pakiet']

            pow_lr = Lr1[['Klient', 'max_percent', 'Grupa promocyjna']]
            stand_lr = Lr2[['Klient', 'max_percent', 'Grupa promocyjna']].rename(columns={'Klient': 'Kod SAP'})

        if not Lg.empty:
            Lg.columns = ['Klient', 'Pakiet']
            Lg = Lg.dropna(subset=['Pakiet', 'Klient'])
            Lg = Lg[~Lg['Pakiet'].str.lower().str.contains('brak')]
            Lg = Lg[Lg['Klient'] != '(puste)']
            
            # Formatujemy Klienta jako tekst bez .0
            Lg['Klient'] = Lg['Klient'].astype(str).str.replace(r'\.0$', '', regex=True).str.strip()

            Lg['pakiet'] = Lg['Pakiet'].apply(extract_numbers_as_text)
            
            # Mapowanie pakietów na format 'Rodzaj pakietu'
            mapa_rodzaj_pakietu = {
                '10+4': '10+4',
                '50+21': '50+21',
                '100+45': '20+9'
            }
            
            pow_lg = Lg[['Klient', 'pakiet']].copy()
            pow_lg['Rodzaj pakietu'] = pow_lg['pakiet'].map(mapa_rodzaj_pakietu)
            pow_lg = pow_lg.dropna(subset=['Rodzaj pakietu'])

            # Rozbijanie na wiersze z odpowiednimi Grupami Promocyjnymi
            rekordy_lg = []
            for _, row in pow_lg.iterrows():
                rodzaj_val = row['Rodzaj pakietu']
                klient_val = row['Klient']

                if rodzaj_val == '50+21':
                    # Dodajemy dwa wiersze dla pakietu 50+21
                    rekordy_lg.append({'Klient': klient_val, 'Rodzaj pakietu': rodzaj_val, 'Grupa promocyjna': 'VITD3M60_50+21'})
                    rekordy_lg.append({'Klient': klient_val, 'Rodzaj pakietu': rodzaj_val, 'Grupa promocyjna': 'VITD3M60_10+4'})
                elif rodzaj_val == '10+4':
                    rekordy_lg.append({'Klient': klient_val, 'Rodzaj pakietu': rodzaj_val, 'Grupa promocyjna': 'VITD3M60_10+4'})
                elif rodzaj_val == '20+9':
                    rekordy_lg.append({'Klient': klient_val, 'Rodzaj pakietu': rodzaj_val, 'Grupa promocyjna': 'VITD3M60_20+9'})

            pow_lg = pd.DataFrame(rekordy_lg)

            st.write("Wiersze dopasowane i zmienione według mapy (Pakiet od 02.07):")
            st.dataframe(pow_lg)

        # --- OBSŁUGA PLIKU IMS ---
        ims = st.file_uploader(label="Wrzuć plik ims_nhd")
        
        if ims:
            ims = pd.read_excel(ims, usecols=[0, 2, 19, 21])
            ims = ims[ims['APD_Czy_istnieje_na_rynku'] == 1]
            ims = ims[ims['APD_Rodzaj_farmaceutyczny'].isin(['AP - Apteka', 'ME - Sklep zielarsko - medyczny', 'PU - Punkt apteczny'])]

            # Czyszczenie kolumn identyfikacyjnych z kropki .0 w IMS
            for col in ims.columns:
                if 'sap' in col.lower() or 'klient' in col.lower():
                    ims[col] = ims[col].astype(str).str.replace(r'\.0$', '', regex=True).str.strip()

            # --- ŁĄCZENIE LR (RABAT) ---
            if 'pow_lr' in locals() and not pow_lr.empty:
                wynik_df_lr = pd.merge(pow_lr, ims, left_on='Klient', right_on='Klient', how='left')
                wynik_df1_lr = wynik_df_lr[['APD_kod_SAP_apteki', 'max_percent', 'Grupa promocyjna']].rename(columns={'APD_kod_SAP_apteki': 'Kod SAP'})
                wynik_df2_lr = wynik_df_lr[['Klient', 'max_percent', 'Grupa promocyjna']].rename(columns={'Klient': 'Kod SAP'})
                
                polaczone_lr = pd.concat([stand_lr, wynik_df1_lr, wynik_df2_lr], axis=0)
                
                # Usuwanie kropki i pustych wartości wygenerowanych przez concat/merge
                polaczone_lr['Kod SAP'] = polaczone_lr['Kod SAP'].astype(str).str.replace(r'\.0$', '', regex=True).str.strip()
                polaczone_lr = polaczone_lr[~polaczone_lr['Kod SAP'].isin(['nan', 'None', ''])]

                posortowane_lr = polaczone_lr.sort_values(by='max_percent', ascending=False)
                ostatecznie_lr = posortowane_lr.drop_duplicates(subset=['Kod SAP', 'Grupa promocyjna'])
                ostatecznie_lr = ostatecznie_lr[ostatecznie_lr['max_percent'] != 0]

            # --- ŁĄCZENIE LG (PAKIET OD 02.07) ---
            if 'pow_lg' in locals() and not pow_lg.empty:
                wynik_df_lg = pd.merge(pow_lg, ims, left_on='Klient', right_on='Klient', how='left')
                wynik_df1_lg = wynik_df_lg[['APD_kod_SAP_apteki', 'Rodzaj pakietu', 'Grupa promocyjna']].rename(columns={'APD_kod_SAP_apteki': 'Kod SAP'})
                wynik_df2_lg = wynik_df_lg[['Klient', 'Rodzaj pakietu', 'Grupa promocyjna']].rename(columns={'Klient': 'Kod SAP'})
                
                polaczone_lg = pd.concat([wynik_df1_lg, wynik_df2_lg], axis=0)
                
                # Usuwanie kropki i pustych wartości wygenerowanych przez concat/merge
                polaczone_lg['Kod SAP'] = polaczone_lg['Kod SAP'].astype(str).str.replace(r'\.0$', '', regex=True).str.strip()
                polaczone_lg = polaczone_lg[~polaczone_lg['Kod SAP'].isin(['nan', 'None', ''])]

                ostatecznie_lg = polaczone_lg.dropna(subset=['Kod SAP']).drop_duplicates(subset=['Kod SAP', 'Rodzaj pakietu', 'Grupa promocyjna'])

            # --- PIERWSZY MONITORING: GENEROWANIE PLIKU ---
            st.write('Jeśli to pierwszy monitoring, pobierz ten plik. Jeśli nie, wrzuć plik z poprzedniego monitoringu poniżej.')
            excel_file = io.BytesIO()
            
            with pd.ExcelWriter(excel_file, engine='xlsxwriter') as writer:
                if 'ostatecznie_lr' in locals() and not ostatecznie_lr.empty:
                    ostatecznie_lr.to_excel(writer, index=False, sheet_name='Rabat')
                if 'ostatecznie_lg' in locals() and not ostatecznie_lg.empty:
                    ostatecznie_lg.to_excel(writer, index=False, sheet_name='Pakiet od 02.07')

            excel_file.seek(0)
            st.download_button(
                label='Pobierz, jeśli to pierwszy monitoring',
                data=excel_file,
                file_name='czy_dodac.xlsx',
                mime='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
            )

            # --- PORÓWNANIE Z POPRZEDNIM MONITORINGIEM ---
            poprzedni = st.file_uploader(label="Wrzuć plik z poprzedniego monitoringu")
            
            if poprzedni:
                xls_pop = pd.ExcelFile(poprzedni)
                
                # Porównanie Rabat
                if 'Rabat' in xls_pop.sheet_names and 'ostatecznie_lr' in locals():
                    poprzedni_lr = pd.read_excel(poprzedni, sheet_name='Rabat')
                    poprzedni_lr = poprzedni_lr.rename(columns={'max_percent': 'old_percent'})
                    
                    ostatecznie_lr['Kod SAP'] = ostatecznie_lr['Kod SAP'].astype(str).str.replace(r'\.0$', '', regex=True).str.strip()
                    poprzedni_lr['Kod SAP'] = poprzedni_lr['Kod SAP'].astype(str).str.replace(r'\.0$', '', regex=True).str.strip()
                    
                    result_lr = ostatecznie_lr.merge(
                        poprzedni_lr[['Kod SAP', 'Grupa promocyjna', 'old_percent']],
                        on=['Kod SAP', 'Grupa promocyjna'],
                        how='left'
                    )
                    result_lr['old_percent'] = result_lr['old_percent'].fillna(0)
                    result_lr['Czy dodać'] = result_lr.apply(
                        lambda row: 'DODAJ' if row['max_percent'] > row['old_percent'] else '',
                        axis=1
                    )
                else:
                    result_lr = ostatecznie_lr.copy() if 'ostatecznie_lr' in locals() else pd.DataFrame()
                    if not result_lr.empty:
                        result_lr['Czy dodać'] = 'DODAJ'

                # Porównanie Pakiet od 02.07
                if 'Pakiet od 02.07' in xls_pop.sheet_names and 'ostatecznie_lg' in locals():
                    poprzedni_lg = pd.read_excel(poprzedni, sheet_name='Pakiet od 02.07')
                    
                    # Obsługa potencjalnej wstecznej kompatybilności, gdyby w starym pliku była jeszcze nazwa 'Nielogiczne'
                    if 'Nielogiczne' in poprzedni_lg.columns and 'Rodzaj pakietu' not in poprzedni_lg.columns:
                        poprzedni_lg = poprzedni_lg.rename(columns={'Nielogiczne': 'Rodzaj pakietu'})

                    poprzedni_lg['Kod SAP'] = poprzedni_lg['Kod SAP'].astype(str).str.replace(r'\.0$', '', regex=True).str.strip()
                    ostatecznie_lg['Kod SAP'] = ostatecznie_lg['Kod SAP'].astype(str).str.replace(r'\.0$', '', regex=True).str.strip()

                    result_lg = pd.concat([ostatecznie_lg, poprzedni_lg], ignore_index=True)
                    result_lg = result_lg.drop_duplicates(subset=['Kod SAP', 'Rodzaj pakietu', 'Grupa promocyjna'], keep='first')
                    
                    pary_poprzednie = set(zip(poprzedni_lg['Kod SAP'], poprzedni_lg['Rodzaj pakietu'], poprzedni_lg['Grupa promocyjna']))
                    result_lg['Czy dodać'] = result_lg.apply(
                        lambda row: '' if (row['Kod SAP'], row['Rodzaj pakietu'], row['Grupa promocyjna']) in pary_poprzednie else 'DODAJ',
                        axis=1
                    )
                else:
                    result_lg = ostatecznie_lg.copy() if 'ostatecznie_lg' in locals() else pd.DataFrame()
                    if not result_lg.empty:
                        result_lg['Czy dodać'] = 'DODAJ'

                # --- EXPORT PLIKU Z "CZY DODAĆ" ---
                excel_file1 = io.BytesIO()
                with pd.ExcelWriter(excel_file1, engine='xlsxwriter') as writer:
                    if 'result_lr' in locals() and not result_lr.empty:
                        result_lr.to_excel(writer, index=False, sheet_name='Rabat')
                    if 'result_lg' in locals() and not result_lg.empty:
                        result_lg.to_excel(writer, index=False, sheet_name='Pakiet od 02.07')

                excel_file1.seek(0)
                nazwa_pliku = f"VIT_D_{dzisiejsza_data}.xlsx"
                st.download_button(
                    label='Kliknij aby pobrać plik z kodami, które kody należy dodać',
                    data=excel_file1,
                    file_name=nazwa_pliku,
                    mime='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
                )

                # --- EXPORT PLIKU "FORMUŁA MAX" (DO NASTĘPNEGO MONITORINGU) ---
                if 'result_lr' in locals() and not result_lr.empty:
                    result_lr_fm = result_lr.drop(columns=['old_percent', 'Czy dodać'], errors='ignore')
                else:
                    result_lr_fm = pd.DataFrame()

                if 'result_lg' in locals() and not result_lg.empty:
                    result_lg_fm = result_lg.drop(columns=['Czy dodać'], errors='ignore')
                else:
                    result_lg_fm = pd.DataFrame()

                excel_file2 = io.BytesIO()
                with pd.ExcelWriter(excel_file2, engine='xlsxwriter') as writer:
                    if not result_lr_fm.empty:
                        result_lr_fm.to_excel(writer, index=False, sheet_name='Rabat')
                    if not result_lg_fm.empty:
                        result_lg_fm.to_excel(writer, index=False, sheet_name='Pakiet od 02.07')

                excel_file2.seek(0)
                nazwa_pliku_fm = f"FM_VIT_D_{dzisiejsza_data}.xlsx"
                st.download_button(
                    label='Pobierz nowy plik FORMUŁA MAX',
                    data=excel_file2,
                    file_name=nazwa_pliku_fm,
                    mime='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
                )



        






    
    







        


















    
