# -*- coding: utf-8 -*-
"""Soczyste rabaty.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bfU5lwdNa2GOPWmQ9-URaf30VnlBzQC0
"""

#importowanie potrzebnych bibliotek
import os
import openpyxl
import streamlit as st
import pandas as pd
import numpy as np
import altair as alt
import plotly.express as px
import plotly.graph_objects as go
from urllib.request import urlopen
import json
import io
import datetime
import re




st.set_page_config(page_title='Monitoringi AUTOMATY', layout='wide')


sekcja = st.sidebar.radio(
    'Wybierz monitoring:',
    ('Cera+','Musy','Panthenol', 'Plastry','Plastry Partner','Standy wrzesień-marzec','Symetykon','Vit D','Zimówka')
 )

tabs_font_css = """
<style>
div[class*="stTextInput"] label {
  font-size: 26px;
  color: black;
}
div[class*="stSelectbox"] label {
  font-size: 26px;
  color: black;
}
</style>
"""
#POTRZEBNE FUNKCJE
#1 Funkcja do wyodrębnienia wartości procentowej
def extract_percentage(text):
    import re
    match = re.search(r'(\d+,\d+|\d+)%', text)
    return match.group(0) if match else ''

#2 Funkcja do konwersji wartości procentowej na float
def percentage_to_float(percentage_str):
    if pd.isna(percentage_str) or not percentage_str:
        return 0.0  # Zmieniono na 0.0, aby brakujące wartości były traktowane jako 0
    # Zamiana przecinka na kropkę, usunięcie znaku '%'
    return float(percentage_str.replace(',', '.').replace('%', ''))

def extract_numbers_as_text(text):
    numbers = re.findall(r'\d+', text)
    return f"{numbers[0]}+{numbers[1]}" if len(numbers) >= 2 else None


dzisiejsza_data = datetime.datetime.now().strftime("%d.%m.%Y")


############################################################################### PLASTRY PARTNER ##############################################################################################
if sekcja == 'Plastry Partner':
    st.write(tabs_font_css, unsafe_allow_html=True)

    df = st.file_uploader(
    label = "Wrzuć plik - Plastry Partner"
    )
    
    if df:
        # Pobieramy listę dostępnych arkuszy
        xls = pd.ExcelFile(df)
        
        # Sprawdzamy, które arkusze są dostępne i wczytujemy odpowiednie dane
        if 'Rabat_PD' in xls.sheet_names:
            R1 = pd.read_excel(df, sheet_name='Rabat_PD', skiprows=11, usecols=[1, 3, 9])
            st.write("Dane z arkusza Rabat_PD:")
            st.write(R1.head())
            
        if 'Rabat_powiązanie' in xls.sheet_names:
            R2 = pd.read_excel(df, sheet_name='Rabat_powiązanie', skiprows=9, usecols=[1, 3, 9])
            st.write("Dane z arkusza Rabat_powiązanie:")
            st.write(R2.head())

        if 'Rabat, gaza_PD' in xls.sheet_names:
            R3 = pd.read_excel(df, sheet_name='Rabat, gaza_PD', skiprows=9, usecols=[1, 3, 9])
            st.write("Dane z arkusza Rabat, gaza_PD:")
            st.write(R3.head())
            
        if 'Rabat, gaza_powiązanie' in xls.sheet_names:
            R4 = pd.read_excel(df, sheet_name='Rabat, gaza_powiązanie', skiprows=9, usecols=[1, 3, 9])
            st.write("Dane z arkusza Rabat, gaza_powiązanie:")
            st.write(R4.head())

        if 'Rabat, ekspozytor' in xls.sheet_names:
            R5 = pd.read_excel(df, sheet_name='Rabat, ekspozytor', skiprows=12, usecols=[1, 3, 10])
            st.write("Dane z arkusza Rabat, ekspozytor:")
            st.write(R5.head())

        df = pd.concat([R1,R2,R3,R4,R5], axis=0, ignore_index=True)
        
        #usuń braki danych z Kod klienta
        df = df.dropna(subset=['Kod SAP'])
    
        # klient na całkowite
        df = df[df['Klient'] != '(puste)']
        df['Klient'] = df['Klient'].astype(int)
        df['Kod SAP'] = df['Kod SAP'].astype(int)
    
        # Zmiana nazw kolumn
        #df = df.rename(columns={'0.12.1': '12', '0.14.1': '14'})
    
        #Dodaj kolumnę 'SIECIOWY', która będzie zawierać 'SIECIOWY' jeśli w kolumnach '12' lub '14' jest słowo 'powiązanie'
        df['SIECIOWY'] = df.apply(lambda row: 'SIECIOWY' if 'powiązanie' in str(row['Pakiet']).lower() else '', axis=1)
    
        #SPRAWDZENIE CZY DZIAŁA
        df[df['SIECIOWY'] == 'SIECIOWY']
        #DZIAŁA :)
    
        
        # Zastosowanie funkcji do kolumn '12' i '14'
        df['Pakiet'] = df['Pakiet'].apply(extract_percentage)
        #df['14_percent'] = df['14'].apply(extract_percentage)
    
    
        # Konwersja kolumn '12_percent' i '14_percent' na liczby zmiennoprzecinkowe
        df['Pakiet'] = df['Pakiet'].apply(percentage_to_float)
        #df['14_percent'] = df['14_percent'].apply(percentage_to_float)
    
        # Dodaj nową kolumnę 'max_percent' z maksymalnymi wartościami z kolumn '12_percent' i '14_percent'
        df['max_percent'] = df[['Pakiet']].max(axis=1)
    
        # Wybierz wiersze, gdzie 'max_percent' nie jest równa 0
        filtered_df = df[df['Pakiet'] != 0]
    
        standard = filtered_df[filtered_df['SIECIOWY'] != 'SIECIOWY']
        powiazanie = filtered_df[filtered_df['SIECIOWY'] == 'SIECIOWY']
    
        #len(standard), len(powiazanie), len(filtered_df)
    
        standard_ost = standard[['Kod SAP', 'max_percent']]
    
        powiazanie = powiazanie[['Klient','Kod SAP','max_percent']]
    
    
        #TERAZ IMS
        ims = st.file_uploader(
            label = "Wrzuć plik ims_nhd"
        )
    
        if ims:
            ims = pd.read_excel(ims, usecols=[0,2,19,21])
            st.write(ims.head())
    
        ims = ims[ims['APD_Czy_istnieje_na_rynku']==1]
        ims = ims[ims['APD_Rodzaj_farmaceutyczny'].isin(['AP - Apteka','ME - Sklep zielarsko - medyczny','PU - Punkt apteczny'])]
    
        wynik_df = pd.merge(powiazanie, ims, left_on='Klient', right_on='Klient', how='left')
    
        #Wybór potrzebnych kolumn: 'APD_kod_SAP_apteki' i 'max_percent'
        wynik_df = wynik_df[['Klient','APD_kod_SAP_apteki', 'max_percent']]
    
    
        #to są kody SAP
        wynik_df1 = wynik_df.rename(columns={'APD_kod_SAP_apteki': 'Kod SAP'})
        wynik_df1 = wynik_df1[['Kod SAP','max_percent']]
        #wynik_df1
    
        #to są kody powiazan
        wynik_df2 = wynik_df.rename(columns={'Klient': 'Kod SAP'})
        wynik_df2 = wynik_df2[['Kod SAP','max_percent']]
        #wynik_df2
    
        #POŁĄCZYĆ wynik_df z standard_ost
        polaczone = pd.concat([standard_ost, wynik_df1, wynik_df2], axis = 0)
      
        posortowane = polaczone.sort_values(by='max_percent', ascending=False)
    
        ostatecznie = posortowane.drop_duplicates(subset=['Kod SAP','max_percent'])
    
    
        st.write('Jeśli to pierwszy monitoring, pobierz ten plik, jeśli nie, wrzuć plik z poprzedniego monitoringu i NIE POBIERAJ TEGO PLIKU')
        excel_file = io.BytesIO()
        with pd.ExcelWriter(excel_file, engine='xlsxwriter') as writer:
            ostatecznie.to_excel(writer, index=False, sheet_name='Sheet1')
        excel_file.seek(0)  # Resetowanie wskaźnika do początku pliku
    
        # Umożliwienie pobrania pliku Excel
        st.download_button(
            label='Pobierz, jeśli to pierwszy monitoring',
            data=excel_file,
            file_name='czy_dodac.xlsx',
            mime='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
        )
    
        #plik z poprzedniego monitoringu
        poprzedni = st.file_uploader(
            label = "Wrzuć plik z poprzedniego monitoringu"
        )
    
        if poprzedni:
            poprzedni = pd.read_excel(poprzedni)
            st.write(poprzedni.head())
    
        poprzedni = poprzedni.rename(columns={'max_percent': 'old_percent'})
        # Wykonanie left join, dodanie 'old_percent' do pliku 'ostatecznie'
        result = ostatecznie.merge(poprzedni[['Kod SAP', 'old_percent']], left_on=['Kod SAP', 'max_percent'], right_on=['Kod SAP', 'old_percent'], how='left', indicator=True)
        result['old_percent'] = result['old_percent'].fillna(0)
        result['Czy dodać'] = result['_merge'].apply(lambda x: 'DODAJ' if x == 'left_only' else '')
        #result['Czy dodać'] = result.apply(lambda row: 'DODAJ' if row['max_percent'] > row['old_percent'] else '', axis=1)
        #result = result.drop_duplicates(subset=['Kod SAP','max_percent','old_percent','Czy dodać'])
        result = result.drop(columns=['old_percent', '_merge'])
        st.write('Kliknij aby pobrać plik z kodami, które kody należy dodać')
    
        excel_file1 = io.BytesIO()
        with pd.ExcelWriter(excel_file1, engine='xlsxwriter') as writer:
            result.to_excel(writer, index=False, sheet_name='Sheet1')
        excel_file1.seek(0)  # Resetowanie wskaźnika do początku pliku
    
        nazwa_pliku1 = f"Plastry_Partner_{dzisiejsza_data}.xlsx"
        #Umożliwienie pobrania pliku Excel
        st.download_button(
            label='Pobierz',
            data=excel_file1,
            file_name=nazwa_pliku1,
            mime='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
        )
    
        result = result.drop(columns=['Czy dodać'])
    
    
        st.write('Kliknij, aby pobrać plik z formułą max do następnego monitoringu')
        excel_file2 = io.BytesIO()
        with pd.ExcelWriter(excel_file2, engine='xlsxwriter') as writer:
            result.to_excel(writer, index=False, sheet_name='Sheet1')
        excel_file1.seek(0)  # Resetowanie wskaźnika do początku pliku
    
        nazwa_pliku = f"FM_Plastry_Partner_{dzisiejsza_data}.xlsx"
        # Umożliwienie pobrania pliku Excel
        st.download_button(
            label='Pobierz nowy plik FORMUŁA MAX',
            data=excel_file2,
            file_name = nazwa_pliku,
            mime='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
        )



############################################################################# Standy wrzesień-marzec################################################################
if sekcja == 'Standy wrzesień-marzec':
    st.write(tabs_font_css, unsafe_allow_html=True)

    df = st.file_uploader(
        label = "Wrzuć plik Cykl - Standy wrzesień-marzec"
    )
    if df:
        df = pd.read_excel(df, sheet_name = 'Rabat', skiprows = 16, usecols = [1,2,9])
        st.write(df.head())


    #usuń braki danych z Kod klienta
    df = df.dropna(subset=['Kod klienta'])

    # klient na całkowite
    df['KLIENT'] = df['KLIENT'].astype(int)
    df['Kod klienta'] = df['Kod klienta'].astype(int)

    # Zmiana nazw kolumn
    df = df.rename(columns={'0.16.2': '16'})

    #Dodaj kolumnę 'SIECIOWY', która będzie zawierać 'SIECIOWY' jeśli w kolumnach '12' lub '14' jest słowo 'powiązanie'
    df['SIECIOWY'] = df.apply(lambda row: 'SIECIOWY' if 'powiązanie' in str(row['16']).lower() else '', axis=1)

    #SPRAWDZENIE CZY DZIAŁA
    #df[df['SIECIOWY'] == 'SIECIOWY']
    #DZIAŁA :)

    
    # Zastosowanie funkcji do kolumn '12' i '14'
    df['16_percent'] = df['16'].apply(extract_percentage)


    # Konwersja kolumn '12_percent' i '14_percent' na liczby zmiennoprzecinkowe
    df['16_percent'] = df['16_percent'].apply(percentage_to_float)

    # Dodaj nową kolumnę 'max_percent' z maksymalnymi wartościami z kolumn '12_percent' i '14_percent'
    df['max_percent'] = df[['16_percent']].max(axis=1)

    # Wybierz wiersze, gdzie 'max_percent' nie jest równa 0
    filtered_df = df[df['max_percent'] != 0]

    standard = filtered_df[filtered_df['SIECIOWY'] != 'SIECIOWY']
    powiazanie = filtered_df[filtered_df['SIECIOWY'] == 'SIECIOWY']

    #len(standard), len(powiazanie), len(filtered_df)

    standard_ost = standard[['Kod klienta', 'max_percent']]

    powiazanie = powiazanie[['KLIENT','Kod klienta','max_percent']]


    #TERAZ IMS
    ims = st.file_uploader(
        label = "Wrzuć plik ims_nhd"
    )

    if ims:
        ims = pd.read_excel(ims, usecols=[0,2,19,21])
        st.write(ims.head())

    ims = ims[ims['APD_Czy_istnieje_na_rynku']==1]
    ims = ims[ims['APD_Rodzaj_farmaceutyczny'].isin(['AP - Apteka','ME - Sklep zielarsko - medyczny','PU - Punkt apteczny'])]

    wynik_df = pd.merge(powiazanie, ims, left_on='KLIENT', right_on='Klient', how='left')

    #Wybór potrzebnych kolumn: 'APD_kod_SAP_apteki' i 'max_percent'
    wynik_df = wynik_df[['KLIENT','APD_kod_SAP_apteki', 'max_percent']]


    #to są kody SAP
    wynik_df1 = wynik_df.rename(columns={'APD_kod_SAP_apteki': 'Kod klienta'})
    wynik_df1 = wynik_df1[['Kod klienta','max_percent']]
    #wynik_df1

    #to są kody powiazan
    wynik_df2 = wynik_df.rename(columns={'KLIENT': 'Kod klienta'})
    wynik_df2 = wynik_df2[['Kod klienta','max_percent']]
    #wynik_df2

    #POŁĄCZYĆ wynik_df z standard_ost
    polaczone = pd.concat([standard_ost, wynik_df1, wynik_df2], axis = 0)
  
    posortowane = polaczone.sort_values(by='max_percent', ascending=False)

    ostatecznie = posortowane.drop_duplicates(subset='Kod klienta')


    st.write('Jeśli to pierwszy monitoring, pobierz ten plik, jeśli nie, wrzuć plik z poprzedniego monitoringu i NIE POBIERAJ TEGO PLIKU')
    excel_file = io.BytesIO()
    with pd.ExcelWriter(excel_file, engine='xlsxwriter') as writer:
        ostatecznie.to_excel(writer, index=False, sheet_name='Sheet1')
    excel_file.seek(0)  # Resetowanie wskaźnika do początku pliku

    # Umożliwienie pobrania pliku Excel
    st.download_button(
        label='Pobierz, jeśli to pierwszy monitoring',
        data=excel_file,
        file_name='czy_dodac.xlsx',
        mime='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
    )

    #plik z poprzedniego monitoringu
    poprzedni = st.file_uploader(
        label = "Wrzuć plik z poprzedniego monitoringu"
    )

    if poprzedni:
        poprzedni = pd.read_excel(poprzedni)
        st.write(poprzedni.head())

    poprzedni = poprzedni.rename(columns={'max_percent': 'old_percent'})
    # Wykonanie left join, dodanie 'old_percent' do pliku 'ostatecznie'
    result = ostatecznie.merge(poprzedni[['Kod klienta', 'old_percent']], on='Kod klienta', how='left')
    result['old_percent'] = result['old_percent'].fillna(0)
    result['Czy dodać'] = result.apply(lambda row: 'DODAJ' if row['max_percent'] > row['old_percent'] else '', axis=1)
    st.write('Kliknij aby pobrać plik z kodami, które kody należy dodać')

    excel_file1 = io.BytesIO()
    with pd.ExcelWriter(excel_file1, engine='xlsxwriter') as writer:
        result.to_excel(writer, index=False, sheet_name='Sheet1')
    excel_file1.seek(0)  # Resetowanie wskaźnika do początku pliku

    nazwa_pliku1 = f"STANDY_w-m_{dzisiejsza_data}.xlsx"
    #Umożliwienie pobrania pliku Excel
    st.download_button(
        label='Pobierz',
        data=excel_file1,
        file_name=nazwa_pliku1,
        mime='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
    )

    result = result.drop(columns=['old_percent', 'Czy dodać'])


    st.write('Kliknij, aby pobrać plik z formułą max do następnego monitoringu')
    excel_file2 = io.BytesIO()
    with pd.ExcelWriter(excel_file2, engine='xlsxwriter') as writer:
        result.to_excel(writer, index=False, sheet_name='Sheet1')
    excel_file1.seek(0)  # Resetowanie wskaźnika do początku pliku

    nazwa_pliku = f"FM_STANDY_w-m_{dzisiejsza_data}.xlsx"
    # Umożliwienie pobrania pliku Excel
    st.download_button(
        label='Pobierz nowy plik FORMUŁA MAX',
        data=excel_file2,
        file_name = nazwa_pliku,
        mime='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
    )


############################################################################### MUSY ##############################################################################################
if sekcja == 'Musy':
    st.write(tabs_font_css, unsafe_allow_html=True)

    df = st.file_uploader(
    label = "Wrzuć plik - Musy"
    )
    if df:
        df = pd.read_excel(df, sheet_name = 'Rabat', skiprows = 12, usecols = [1,3,9])
        st.write(df.head())
        
        #usuń braki danych z Kod klienta
    df = df.dropna(subset=['Kod SAP'])

    # klient na całkowite
    df = df[df['Klient'] != '(puste)']
    df['Klient'] = df['Klient'].astype(int)
    df['Kod SAP'] = df['Kod SAP'].astype(int)

    # Zmiana nazw kolumn
    #df = df.rename(columns={'0.12.1': '12', '0.14.1': '14'})

    #Dodaj kolumnę 'SIECIOWY', która będzie zawierać 'SIECIOWY' jeśli w kolumnach '12' lub '14' jest słowo 'powiązanie'
    df['SIECIOWY'] = df.apply(lambda row: 'SIECIOWY' if 'powiązanie' in str(row['Pakiet']).lower() else '', axis=1)

    #SPRAWDZENIE CZY DZIAŁA
    df[df['SIECIOWY'] == 'SIECIOWY']
    #DZIAŁA :)

    
    # Zastosowanie funkcji do kolumn '12' i '14'
    df['Pakiet'] = df['Pakiet'].apply(extract_percentage)
    #df['14_percent'] = df['14'].apply(extract_percentage)


    # Konwersja kolumn '12_percent' i '14_percent' na liczby zmiennoprzecinkowe
    df['Pakiet'] = df['Pakiet'].apply(percentage_to_float)
    #df['14_percent'] = df['14_percent'].apply(percentage_to_float)

    # Dodaj nową kolumnę 'max_percent' z maksymalnymi wartościami z kolumn '12_percent' i '14_percent'
    df['max_percent'] = df[['Pakiet']].max(axis=1)

    # Wybierz wiersze, gdzie 'max_percent' nie jest równa 0
    filtered_df = df[df['max_percent'] != 0]

    standard = filtered_df[filtered_df['SIECIOWY'] != 'SIECIOWY']
    powiazanie = filtered_df[filtered_df['SIECIOWY'] == 'SIECIOWY']

    #len(standard), len(powiazanie), len(filtered_df)

    standard_ost = standard[['Kod SAP', 'max_percent']]

    powiazanie = powiazanie[['Klient','Kod SAP','max_percent']]


    #TERAZ IMS
    ims = st.file_uploader(
        label = "Wrzuć plik ims_nhd"
    )

    if ims:
        ims = pd.read_excel(ims, usecols=[0,2,19,21])
        st.write(ims.head())

    ims = ims[ims['APD_Czy_istnieje_na_rynku']==1]
    ims = ims[ims['APD_Rodzaj_farmaceutyczny'].isin(['AP - Apteka','ME - Sklep zielarsko - medyczny','PU - Punkt apteczny'])]

    wynik_df = pd.merge(powiazanie, ims, left_on='Klient', right_on='Klient', how='left')

    #Wybór potrzebnych kolumn: 'APD_kod_SAP_apteki' i 'max_percent'
    wynik_df = wynik_df[['Klient','APD_kod_SAP_apteki', 'max_percent']]


    #to są kody SAP
    wynik_df1 = wynik_df.rename(columns={'APD_kod_SAP_apteki': 'Kod SAP'})
    wynik_df1 = wynik_df1[['Kod SAP','max_percent']]
    #wynik_df1

    #to są kody powiazan
    wynik_df2 = wynik_df.rename(columns={'Klient': 'Kod SAP'})
    wynik_df2 = wynik_df2[['Kod SAP','max_percent']]
    #wynik_df2

    #POŁĄCZYĆ wynik_df z standard_ost
    polaczone = pd.concat([standard_ost, wynik_df1, wynik_df2], axis = 0)
  
    posortowane = polaczone.sort_values(by='max_percent', ascending=False)

    ostatecznie = posortowane.drop_duplicates(subset='Kod SAP')


    st.write('Jeśli to pierwszy monitoring, pobierz ten plik, jeśli nie, wrzuć plik z poprzedniego monitoringu i NIE POBIERAJ TEGO PLIKU')
    excel_file = io.BytesIO()
    with pd.ExcelWriter(excel_file, engine='xlsxwriter') as writer:
        ostatecznie.to_excel(writer, index=False, sheet_name='Sheet1')
    excel_file.seek(0)  # Resetowanie wskaźnika do początku pliku

    # Umożliwienie pobrania pliku Excel
    st.download_button(
        label='Pobierz, jeśli to pierwszy monitoring',
        data=excel_file,
        file_name='czy_dodac.xlsx',
        mime='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
    )

    #plik z poprzedniego monitoringu
    poprzedni = st.file_uploader(
        label = "Wrzuć plik z poprzedniego monitoringu"
    )

    if poprzedni:
        poprzedni = pd.read_excel(poprzedni)
        st.write(poprzedni.head())

    poprzedni = poprzedni.rename(columns={'max_percent': 'old_percent'})
    # Wykonanie left join, dodanie 'old_percent' do pliku 'ostatecznie'
    result = ostatecznie.merge(poprzedni[['Kod SAP', 'old_percent']], on='Kod SAP', how='left')
    result['old_percent'] = result['old_percent'].fillna(0)
    result['Czy dodać'] = result.apply(lambda row: 'DODAJ' if row['max_percent'] > row['old_percent'] else '', axis=1)
    st.write('Kliknij aby pobrać plik z kodami, które kody należy dodać')

    excel_file1 = io.BytesIO()
    with pd.ExcelWriter(excel_file1, engine='xlsxwriter') as writer:
        result.to_excel(writer, index=False, sheet_name='Sheet1')
    excel_file1.seek(0)  # Resetowanie wskaźnika do początku pliku

    nazwa_pliku1 = f"Musy_{dzisiejsza_data}.xlsx"
    #Umożliwienie pobrania pliku Excel
    st.download_button(
        label='Pobierz',
        data=excel_file1,
        file_name=nazwa_pliku1,
        mime='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
    )

    result = result.drop(columns=['old_percent', 'Czy dodać'])


    st.write('Kliknij, aby pobrać plik z formułą max do następnego monitoringu')
    excel_file2 = io.BytesIO()
    with pd.ExcelWriter(excel_file2, engine='xlsxwriter') as writer:
        result.to_excel(writer, index=False, sheet_name='Sheet1')
    excel_file1.seek(0)  # Resetowanie wskaźnika do początku pliku

    nazwa_pliku = f"FM_Musy_{dzisiejsza_data}.xlsx"
    # Umożliwienie pobrania pliku Excel
    st.download_button(
        label='Pobierz nowy plik FORMUŁA MAX',
        data=excel_file2,
        file_name = nazwa_pliku,
        mime='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
    )


############################################################################### PLASTRY ##############################################################################################
if sekcja == 'Plastry':
    st.write(tabs_font_css, unsafe_allow_html=True)

    df = st.file_uploader(
    label = "Wrzuć plik - Plastry"
    )
    
    if df:
        # Pobieramy listę dostępnych arkuszy
        xls = pd.ExcelFile(df)
        
        # Sprawdzamy, które arkusze są dostępne i wczytujemy odpowiednie dane
        if 'Rabat_PD' in xls.sheet_names:
            R1 = pd.read_excel(df, sheet_name='Rabat_PD', skiprows=11, usecols=[1, 3, 9])
            st.write("Dane z arkusza Rabat_PD:")
            st.write(R1.head())
            
        if 'Rabat_powiązanie' in xls.sheet_names:
            R2 = pd.read_excel(df, sheet_name='Rabat_powiązanie', skiprows=9, usecols=[1, 3, 9])
            st.write("Dane z arkusza Rabat_powiązanie:")
            st.write(R2.head())

        if 'Rabat, gaza_PD' in xls.sheet_names:
            R3 = pd.read_excel(df, sheet_name='Rabat, gaza_PD', skiprows=9, usecols=[1, 3, 9])
            st.write("Dane z arkusza Rabat, gaza_PD:")
            st.write(R3.head())
            
        if 'Rabat, gaza_powiązanie' in xls.sheet_names:
            R4 = pd.read_excel(df, sheet_name='Rabat, gaza_powiązanie', skiprows=9, usecols=[1, 3, 9])
            st.write("Dane z arkusza Rabat, gaza_powiązanie:")
            st.write(R4.head())

        if 'Rabat, ekspozytor' in xls.sheet_names:
            R5 = pd.read_excel(df, sheet_name='Rabat, ekspozytor', skiprows=12, usecols=[1, 3, 10])
            st.write("Dane z arkusza Rabat, ekspozytor:")
            st.write(R5.head())

        df = pd.concat([R1,R2,R3,R4,R5], axis=0, ignore_index=True)
        
        #usuń braki danych z Kod klienta
        df = df.dropna(subset=['Kod SAP'])
    
        # klient na całkowite
        df = df[df['Klient'] != '(puste)']
        df['Klient'] = df['Klient'].astype(int)
        df['Kod SAP'] = df['Kod SAP'].astype(int)
    
        # Zmiana nazw kolumn
        #df = df.rename(columns={'0.12.1': '12', '0.14.1': '14'})
    
        #Dodaj kolumnę 'SIECIOWY', która będzie zawierać 'SIECIOWY' jeśli w kolumnach '12' lub '14' jest słowo 'powiązanie'
        df['SIECIOWY'] = df.apply(lambda row: 'SIECIOWY' if 'powiązanie' in str(row['Pakiet']).lower() else '', axis=1)
    
        #SPRAWDZENIE CZY DZIAŁA
        df[df['SIECIOWY'] == 'SIECIOWY']
        #DZIAŁA :)
    
        
        # Zastosowanie funkcji do kolumn '12' i '14'
        df['Pakiet'] = df['Pakiet'].apply(extract_percentage)
        #df['14_percent'] = df['14'].apply(extract_percentage)
    
    
        # Konwersja kolumn '12_percent' i '14_percent' na liczby zmiennoprzecinkowe
        df['Pakiet'] = df['Pakiet'].apply(percentage_to_float)
        #df['14_percent'] = df['14_percent'].apply(percentage_to_float)
    
        # Dodaj nową kolumnę 'max_percent' z maksymalnymi wartościami z kolumn '12_percent' i '14_percent'
        df['max_percent'] = df[['Pakiet']].max(axis=1)
    
        # Wybierz wiersze, gdzie 'max_percent' nie jest równa 0
        filtered_df = df[df['Pakiet'] != 0]
    
        standard = filtered_df[filtered_df['SIECIOWY'] != 'SIECIOWY']
        powiazanie = filtered_df[filtered_df['SIECIOWY'] == 'SIECIOWY']
    
        #len(standard), len(powiazanie), len(filtered_df)
    
        standard_ost = standard[['Kod SAP', 'max_percent']]
    
        powiazanie = powiazanie[['Klient','Kod SAP','max_percent']]
    
    
        #TERAZ IMS
        ims = st.file_uploader(
            label = "Wrzuć plik ims_nhd"
        )
    
        if ims:
            ims = pd.read_excel(ims, usecols=[0,2,19,21])
            st.write(ims.head())
    
        ims = ims[ims['APD_Czy_istnieje_na_rynku']==1]
        ims = ims[ims['APD_Rodzaj_farmaceutyczny'].isin(['AP - Apteka','ME - Sklep zielarsko - medyczny','PU - Punkt apteczny'])]
    
        wynik_df = pd.merge(powiazanie, ims, left_on='Klient', right_on='Klient', how='left')
    
        #Wybór potrzebnych kolumn: 'APD_kod_SAP_apteki' i 'max_percent'
        wynik_df = wynik_df[['Klient','APD_kod_SAP_apteki', 'max_percent']]
    
    
        #to są kody SAP
        wynik_df1 = wynik_df.rename(columns={'APD_kod_SAP_apteki': 'Kod SAP'})
        wynik_df1 = wynik_df1[['Kod SAP','max_percent']]
        #wynik_df1
    
        #to są kody powiazan
        wynik_df2 = wynik_df.rename(columns={'Klient': 'Kod SAP'})
        wynik_df2 = wynik_df2[['Kod SAP','max_percent']]
        #wynik_df2
    
        #POŁĄCZYĆ wynik_df z standard_ost
        polaczone = pd.concat([standard_ost, wynik_df1, wynik_df2], axis = 0)
      
        posortowane = polaczone.sort_values(by='max_percent', ascending=False)
    
        ostatecznie = posortowane.drop_duplicates(subset=['Kod SAP','max_percent'])
    
    
        st.write('Jeśli to pierwszy monitoring, pobierz ten plik, jeśli nie, wrzuć plik z poprzedniego monitoringu i NIE POBIERAJ TEGO PLIKU')
        excel_file = io.BytesIO()
        with pd.ExcelWriter(excel_file, engine='xlsxwriter') as writer:
            ostatecznie.to_excel(writer, index=False, sheet_name='Sheet1')
        excel_file.seek(0)  # Resetowanie wskaźnika do początku pliku
    
        # Umożliwienie pobrania pliku Excel
        st.download_button(
            label='Pobierz, jeśli to pierwszy monitoring',
            data=excel_file,
            file_name='czy_dodac.xlsx',
            mime='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
        )
    
        #plik z poprzedniego monitoringu
        poprzedni = st.file_uploader(
            label = "Wrzuć plik z poprzedniego monitoringu"
        )
    
        if poprzedni:
            poprzedni = pd.read_excel(poprzedni)
            st.write(poprzedni.head())
    
        poprzedni = poprzedni.rename(columns={'max_percent': 'old_percent'})
        # Wykonanie left join, dodanie 'old_percent' do pliku 'ostatecznie'
        result = ostatecznie.merge(poprzedni[['Kod SAP', 'old_percent']], left_on=['Kod SAP', 'max_percent'], right_on=['Kod SAP', 'old_percent'], how='left', indicator=True)
        result['old_percent'] = result['old_percent'].fillna(0)
        result['Czy dodać'] = result['_merge'].apply(lambda x: 'DODAJ' if x == 'left_only' else '')
        #result['Czy dodać'] = result.apply(lambda row: 'DODAJ' if row['max_percent'] > row['old_percent'] else '', axis=1)
        #result = result.drop_duplicates(subset=['Kod SAP','max_percent','old_percent','Czy dodać'])
        result = result.drop(columns=['old_percent', '_merge'])
        st.write('Kliknij aby pobrać plik z kodami, które kody należy dodać')
    
        excel_file1 = io.BytesIO()
        with pd.ExcelWriter(excel_file1, engine='xlsxwriter') as writer:
            result.to_excel(writer, index=False, sheet_name='Sheet1')
        excel_file1.seek(0)  # Resetowanie wskaźnika do początku pliku
    
        nazwa_pliku1 = f"Plastry_{dzisiejsza_data}.xlsx"
        #Umożliwienie pobrania pliku Excel
        st.download_button(
            label='Pobierz',
            data=excel_file1,
            file_name=nazwa_pliku1,
            mime='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
        )
    
        result = result.drop(columns=['Czy dodać'])
    
    
        st.write('Kliknij, aby pobrać plik z formułą max do następnego monitoringu')
        excel_file2 = io.BytesIO()
        with pd.ExcelWriter(excel_file2, engine='xlsxwriter') as writer:
            result.to_excel(writer, index=False, sheet_name='Sheet1')
        excel_file1.seek(0)  # Resetowanie wskaźnika do początku pliku
    
        nazwa_pliku = f"FM_Plastry_{dzisiejsza_data}.xlsx"
        # Umożliwienie pobrania pliku Excel
        st.download_button(
            label='Pobierz nowy plik FORMUŁA MAX',
            data=excel_file2,
            file_name = nazwa_pliku,
            mime='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
        )

############################################################################# CERA+ ################################################################
if sekcja == 'Cera+':
    st.write(tabs_font_css, unsafe_allow_html=True)

    df = st.file_uploader(
        label = "Wrzuć plik Cykl - Cera+"
    )
    if df:
        df = pd.read_excel(df, sheet_name = 'Rabat', skiprows = 14, usecols = [1,3,9])
        st.write(df.head())


    #usuń braki danych z Kod klienta
    df = df.dropna(subset=['Kod SAP'])

    # klient na całkowite
    df = df[df['Klient'] != '(puste)']
    df['Klient'] = df['Klient'].astype(int)
    df['Kod SAP'] = df['Kod SAP'].astype(int)

    # Zmiana nazw kolumn
    #df = df.rename(columns={'0.16.2': '16'})

    #Dodaj kolumnę 'SIECIOWY', która będzie zawierać 'SIECIOWY' jeśli w kolumnach '12' lub '14' jest słowo 'powiązanie'
    df['SIECIOWY'] = df.apply(lambda row: 'SIECIOWY' if 'powiązanie' in str(row['Pakiet']).lower() else '', axis=1)

    #SPRAWDZENIE CZY DZIAŁA
    #df[df['SIECIOWY'] == 'SIECIOWY']
    #DZIAŁA :)

    
    # Zastosowanie funkcji do kolumn '12' i '14'
    df['Pakiet'] = df['Pakiet'].apply(extract_percentage)


    # Konwersja kolumn '12_percent' i '14_percent' na liczby zmiennoprzecinkowe
    df['Pakiet'] = df['Pakiet'].apply(percentage_to_float)

    # Dodaj nową kolumnę 'max_percent' z maksymalnymi wartościami z kolumn '12_percent' i '14_percent'
    df['max_percent'] = df[['Pakiet']].max(axis=1)

    # Wybierz wiersze, gdzie 'max_percent' nie jest równa 0
    filtered_df = df[df['max_percent'] != 0]

    standard = filtered_df[filtered_df['SIECIOWY'] != 'SIECIOWY']
    powiazanie = filtered_df[filtered_df['SIECIOWY'] == 'SIECIOWY']

    #len(standard), len(powiazanie), len(filtered_df)

    standard_ost = standard[['Kod SAP', 'max_percent']]

    powiazanie = powiazanie[['Klient','Kod SAP','max_percent']]


    #TERAZ IMS
    ims = st.file_uploader(
        label = "Wrzuć plik ims_nhd"
    )

    if ims:
        ims = pd.read_excel(ims, usecols=[0,2,19,21])
        st.write(ims.head())

    ims = ims[ims['APD_Czy_istnieje_na_rynku']==1]
    ims = ims[ims['APD_Rodzaj_farmaceutyczny'].isin(['AP - Apteka','ME - Sklep zielarsko - medyczny','PU - Punkt apteczny'])]

    wynik_df = pd.merge(powiazanie, ims, left_on='Klient', right_on='Klient', how='left')

    #Wybór potrzebnych kolumn: 'APD_kod_SAP_apteki' i 'max_percent'
    wynik_df = wynik_df[['Klient','APD_kod_SAP_apteki', 'max_percent']]


    #to są kody SAP
    wynik_df1 = wynik_df.rename(columns={'APD_kod_SAP_apteki': 'Kod SAP'})
    wynik_df1 = wynik_df1[['Kod SAP','max_percent']]
    #wynik_df1

    #to są kody powiazan
    wynik_df2 = wynik_df.rename(columns={'Klient': 'Kod SAP'})
    wynik_df2 = wynik_df2[['Kod SAP','max_percent']]
    #wynik_df2

    #POŁĄCZYĆ wynik_df z standard_ost
    polaczone = pd.concat([standard_ost, wynik_df1, wynik_df2], axis = 0)
  
    posortowane = polaczone.sort_values(by='max_percent', ascending=False)

    ostatecznie = posortowane.drop_duplicates(subset='Kod SAP')


    st.write('Jeśli to pierwszy monitoring, pobierz ten plik, jeśli nie, wrzuć plik z poprzedniego monitoringu i NIE POBIERAJ TEGO PLIKU')
    excel_file = io.BytesIO()
    with pd.ExcelWriter(excel_file, engine='xlsxwriter') as writer:
        ostatecznie.to_excel(writer, index=False, sheet_name='Sheet1')
    excel_file.seek(0)  # Resetowanie wskaźnika do początku pliku

    # Umożliwienie pobrania pliku Excel
    st.download_button(
        label='Pobierz, jeśli to pierwszy monitoring',
        data=excel_file,
        file_name='czy_dodac.xlsx',
        mime='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
    )

    #plik z poprzedniego monitoringu
    poprzedni = st.file_uploader(
        label = "Wrzuć plik z poprzedniego monitoringu"
    )

    if poprzedni:
        poprzedni = pd.read_excel(poprzedni)
        st.write(poprzedni.head())

    poprzedni = poprzedni.rename(columns={'max_percent': 'old_percent'})
    # Wykonanie left join, dodanie 'old_percent' do pliku 'ostatecznie'
    result = ostatecznie.merge(poprzedni[['Kod SAP', 'old_percent']], on='Kod SAP', how='left')
    result['old_percent'] = result['old_percent'].fillna(0)
    result['Czy dodać'] = result.apply(lambda row: 'DODAJ' if row['max_percent'] > row['old_percent'] else '', axis=1)
    st.write('Kliknij aby pobrać plik z kodami, które kody należy dodać')

    excel_file1 = io.BytesIO()
    with pd.ExcelWriter(excel_file1, engine='xlsxwriter') as writer:
        result.to_excel(writer, index=False, sheet_name='Sheet1')
    excel_file1.seek(0)  # Resetowanie wskaźnika do początku pliku

    nazwa_pliku1 = f"CERA+_{dzisiejsza_data}.xlsx"
    #Umożliwienie pobrania pliku Excel
    st.download_button(
        label='Pobierz',
        data=excel_file1,
        file_name=nazwa_pliku1,
        mime='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
    )

    result = result.drop(columns=['old_percent', 'Czy dodać'])


    st.write('Kliknij, aby pobrać plik z formułą max do następnego monitoringu')
    excel_file2 = io.BytesIO()
    with pd.ExcelWriter(excel_file2, engine='xlsxwriter') as writer:
        result.to_excel(writer, index=False, sheet_name='Sheet1')
    excel_file1.seek(0)  # Resetowanie wskaźnika do początku pliku

    nazwa_pliku = f"FM_CERA+_{dzisiejsza_data}.xlsx"
    # Umożliwienie pobrania pliku Excel
    st.download_button(
        label='Pobierz nowy plik FORMUŁA MAX',
        data=excel_file2,
        file_name = nazwa_pliku,
        mime='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
    )

############################################################################# Panthenol ################################################################
if sekcja == 'Panthenol':
    st.write(tabs_font_css, unsafe_allow_html=True)

    df_input = st.file_uploader(
        label = "Wrzuć plik Cykl - Panthenol"
    )
    if df_input:
        df = pd.read_excel(df_input, sheet_name = 'Rabat', skiprows = 18, usecols = [1,3,6,10])
        st.write(df.head())

        # usuń braki danych z Kod klienta
        df = df.dropna(subset=['Kod SAP'])
        df = df[df["Kod SAP"] != "(puste)"]

        # klient na całkowite
        df['Klient'] = df['Klient'].astype(int)
        df['Kod SAP'] = df['Kod SAP'].astype(int)

        # Dodaj kolumnę 'SIECIOWY'
        df['SIECIOWY'] = df.apply(lambda row: 'SIECIOWY' if 'powiązanie' in str(row['Pakiet']).lower() else '', axis=1)
        
        # Zastosowanie funkcji do kolumny 'Pakiet'
        df['Pakiet'] = df['Pakiet'].apply(extract_percentage)
        df['Pakiet'] = df['Pakiet'].apply(percentage_to_float)

        # Podział na 3 osobne tabele według podanych indeksów
        df_105210 = df[df['Indeks'] == 105210].copy()
        df_105211 = df[df['Indeks'] == 105211].copy()
        df_105212 = df[df['Indeks'] == 105212].copy()

        # Wyświetlenie wyników w Streamlit
        st.markdown("### Wyniki po podziale na indeksy:")
        st.write("**Tabela dla indeksu 105210:**")
        st.dataframe(df_105210)
        st.write("**Tabela dla indeksu 105211:**")
        st.dataframe(df_105211)
        st.write("**Tabela dla indeksu 105212:**")
        st.dataframe(df_105212)

        # --- PRZETWARZANIE KAŻDEJ Z 3 TABEL (max_percent i filtrowanie) ---
        
        # 1. Indeks 105210
        df_105210['max_percent'] = df_105210[['Pakiet']].max(axis=1)
        filtered_105210 = df_105210[df_105210['max_percent'] != 0]
        standard_105210 = filtered_105210[filtered_105210['SIECIOWY'] != 'SIECIOWY']
        powiazanie_105210 = filtered_105210[filtered_105210['SIECIOWY'] == 'SIECIOWY']
        standard_ost_105210 = standard_105210[['Kod SAP', 'max_percent']]
        powiazanie_105210 = powiazanie_105210[['Klient','Kod SAP','max_percent']]

        # 2. Indeks 105211
        df_105211['max_percent'] = df_105211[['Pakiet']].max(axis=1)
        filtered_105211 = df_105211[df_105211['max_percent'] != 0]
        standard_105211 = filtered_105211[filtered_105211['SIECIOWY'] != 'SIECIOWY']
        powiazanie_105211 = filtered_105211[filtered_105211['SIECIOWY'] == 'SIECIOWY']
        standard_ost_105211 = standard_105211[['Kod SAP', 'max_percent']]
        powiazanie_105211 = powiazanie_105211[['Klient','Kod SAP','max_percent']]

        # 3. Indeks 105212
        df_105212['max_percent'] = df_105212[['Pakiet']].max(axis=1)
        filtered_105212 = df_105212[df_105212['max_percent'] != 0]
        standard_105212 = filtered_105212[filtered_105212['SIECIOWY'] != 'SIECIOWY']
        powiazanie_105212 = filtered_105212[filtered_105212['SIECIOWY'] == 'SIECIOWY']
        standard_ost_105212 = standard_105212[['Kod SAP', 'max_percent']]
        powiazanie_105212 = powiazanie_105212[['Klient','Kod SAP','max_percent']]


        # --- TERAZ IMS ---
        ims_input = st.file_uploader(
            label = "Wrzuć plik ims_nhd"
        )

        if ims_input:
            ims = pd.read_excel(ims_input, usecols=[0,2,19,21])
            st.write(ims.head())

            ims = ims[ims['APD_Czy_istnieje_na_rynku']==1]
            ims = ims[ims['APD_Rodzaj_farmaceutyczny'].isin(['AP - Apteka','ME - Sklep zielarsko - medyczny','PU - Punkt apteczny'])]

            # --- ŁĄCZENIE Z IMS DLA KAŻDEGO INDEKSU OSOBNO ---
            
            # Indeks 105210
            wynik_df_105210 = pd.merge(powiazanie_105210, ims, left_on='Klient', right_on='Klient', how='left')
            wynik_df_105210 = wynik_df_105210[['Klient','APD_kod_SAP_apteki', 'max_percent']]
            wynik_df1_105210 = wynik_df_105210.rename(columns={'APD_kod_SAP_apteki': 'Kod SAP'})[['Kod SAP','max_percent']]
            wynik_df2_105210 = wynik_df_105210.rename(columns={'Klient': 'Kod SAP'})[['Kod SAP','max_percent']]
            polaczone_105210 = pd.concat([standard_ost_105210, wynik_df1_105210, wynik_df2_105210], axis = 0)
            ostatecznie_105210 = polaczone_105210.sort_values(by='max_percent', ascending=False).drop_duplicates(subset='Kod SAP')

            # Indeks 105211
            wynik_df_105211 = pd.merge(powiazanie_105211, ims, left_on='Klient', right_on='Klient', how='left')
            wynik_df_105211 = wynik_df_105211[['Klient','APD_kod_SAP_apteki', 'max_percent']]
            wynik_df1_105211 = wynik_df_105211.rename(columns={'APD_kod_SAP_apteki': 'Kod SAP'})[['Kod SAP','max_percent']]
            wynik_df2_105211 = wynik_df_105211.rename(columns={'Klient': 'Kod SAP'})[['Kod SAP','max_percent']]
            polaczone_105211 = pd.concat([standard_ost_105211, wynik_df1_105211, wynik_df2_105211], axis = 0)
            ostatecznie_105211 = polaczone_105211.sort_values(by='max_percent', ascending=False).drop_duplicates(subset='Kod SAP')

            # Indeks 105212
            wynik_df_105212 = pd.merge(powiazanie_105212, ims, left_on='Klient', right_on='Klient', how='left')
            wynik_df_105212 = wynik_df_105212[['Klient','APD_kod_SAP_apteki', 'max_percent']]
            wynik_df1_105212 = wynik_df_105212.rename(columns={'APD_kod_SAP_apteki': 'Kod SAP'})[['Kod SAP','max_percent']]
            wynik_df2_105212 = wynik_df_105212.rename(columns={'Klient': 'Kod SAP'})[['Kod SAP','max_percent']]
            polaczone_105212 = pd.concat([standard_ost_105212, wynik_df1_105212, wynik_df2_105212], axis = 0)
            ostatecznie_105212 = polaczone_105212.sort_values(by='max_percent', ascending=False).drop_duplicates(subset='Kod SAP')


            # ZAPIS PIERWSZEGO MONITORINGU (3 arkusze w jednym pliku)
            st.write('Jeśli to pierwszy monitoring, pobierz ten plik, jeśli nie, wrzuć plik z poprzedniego monitoringu i NIE POBIERAJ TEGO PLIKU')
            excel_file = io.BytesIO()
            with pd.ExcelWriter(excel_file, engine='xlsxwriter') as writer:
                ostatecznie_105210.to_excel(writer, index=False, sheet_name='105210')
                ostatecznie_105211.to_excel(writer, index=False, sheet_name='105211')
                ostatecznie_105212.to_excel(writer, index=False, sheet_name='105212')
            excel_file.seek(0)

            st.download_button(
                label='Pobierz, jeśli to pierwszy monitoring',
                data=excel_file,
                file_name='czy_dodac.xlsx',
                mime='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
            )


            # --- PLIK Z POPRZEDNIEGO MONITORINGU ---
            poprzedni_input = st.file_uploader(
                label = "Wrzuć plik z poprzedniego monitoringu"
            )

            if poprzedni_input:
                # Wczytujemy wszystkie arkusze z poprzedniego pliku
                poprzedni_sheets = pd.read_excel(poprzedni_input, sheet_name=None)
                
                # Pobieramy dane dla odpowiednich arkuszy (lub domyślny pierwszy arkusz, jeśli nie ma podziału)
                poprzedni_105210 = poprzedni_sheets.get('105210', list(poprzedni_sheets.values())[0]).rename(columns={'max_percent': 'old_percent'})
                poprzedni_105211 = poprzedni_sheets.get('105211', list(poprzedni_sheets.values())[0]).rename(columns={'max_percent': 'old_percent'})
                poprzedni_105212 = wastes = poprzedni_sheets.get('105212', list(poprzedni_sheets.values())[0]).rename(columns={'max_percent': 'old_percent'})

                # Porównanie dla 105210
                res_105210 = ostatecznie_105210.merge(poprzedni_105210[['Kod SAP', 'old_percent']], on='Kod SAP', how='left')
                res_105210['old_percent'] = res_105210['old_percent'].fillna(0)
                res_105210['Czy dodać'] = res_105210.apply(lambda row: 'DODAJ' if row['max_percent'] > row['old_percent'] else '', axis=1)

                # Porównanie dla 105211
                res_105211 = ostatecznie_105211.merge(poprzedni_105211[['Kod SAP', 'old_percent']], on='Kod SAP', how='left')
                res_105211['old_percent'] = res_105211['old_percent'].fillna(0)
                res_105211['Czy dodać'] = res_105211.apply(lambda row: 'DODAJ' if row['max_percent'] > row['old_percent'] else '', axis=1)

                # Porównanie dla 105212
                res_105212 = ostatecznie_105212.merge(poprzedni_105212[['Kod SAP', 'old_percent']], on='Kod SAP', how='left')
                res_105212['old_percent'] = res_105212['old_percent'].fillna(0)
                res_105212['Czy dodać'] = res_105212.apply(lambda row: 'DODAJ' if row['max_percent'] > row['old_percent'] else '', axis=1)

                # GENEROWANIE PLIKU "CZY DODAĆ" Z TRZEMA ARKUSZAMI
                st.write('Kliknij aby pobrać plik z kodami, które kody należy dodać')
                excel_file1 = io.BytesIO()
                with pd.ExcelWriter(excel_file1, engine='xlsxwriter') as writer:
                    res_105210.to_excel(writer, index=False, sheet_name='105210')
                    res_105211.to_excel(writer, index=False, sheet_name='105211')
                    res_105212.to_excel(writer, index=False, sheet_name='105212')
                excel_file1.seek(0)

                nazwa_pliku1 = f"Panthenol_{dzisiejsza_data}.xlsx"
                st.download_button(
                    label='Pobierz',
                    data=excel_file1,
                    file_name=nazwa_pliku1,
                    mime='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
                )

                # CZYSZCZENIE DO FORMUŁY MAX
                res_105210_fm = res_105210.drop(columns=['old_percent', 'Czy dodać'])
                res_105211_fm = res_105211.drop(columns=['old_percent', 'Czy dodać'])
                res_105212_fm = res_105212.drop(columns=['old_percent', 'Czy dodać'])

                # GENEROWANIE NOWEGO PLIKU "FORMUŁA MAX" Z TRZEMA ARKUSZAMI
                st.write('Kliknij, aby pobrać plik z formułą max do następnego monitoringu')
                excel_file2 = io.BytesIO()
                with pd.ExcelWriter(excel_file2, engine='xlsxwriter') as writer:
                    res_105210_fm.to_excel(writer, index=False, sheet_name='105210')
                    res_105211_fm.to_excel(writer, index=False, sheet_name='105211')
                    res_105212_fm.to_excel(writer, index=False, sheet_name='105212')
                excel_file2.seek(0)

                nazwa_pliku = f"FM_Panthenol_{dzisiejsza_data}.xlsx"
                st.download_button(
                    label='Pobierz nowy plik FORMUŁA MAX',
                    data=excel_file2,
                    file_name = nazwa_pliku,
                    mime='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
                )


############################################################################### ZIMÓWKA ##############################################################################################
if sekcja == 'Zimówka':
    st.write(tabs_font_css, unsafe_allow_html=True)

    df = st.file_uploader(
        label="Wrzuć plik - Zimówka"
    )
    
    if df:
        # Pobieramy listę dostępnych arkuszy
        xls = pd.ExcelFile(df)
        
        # Sprawdzamy, które arkusze są dostępne i wczytujemy odpowiednie dane
        if 'Rabat' in xls.sheet_names:
            Lr = pd.read_excel(df, sheet_name='Rabat', skiprows=12, usecols=[1, 6])
            st.write("Dane z arkusza Rabat:")
            st.write(Lr.head())


        # Sprawdzamy, które arkusze są dostępne i wczytujemy odpowiednie dane
        if 'Gratis' in xls.sheet_names:
            Lg = pd.read_excel(df, sheet_name='Gratis', skiprows=7, usecols=[1, 3, 9])
            st.write("Dane z arkusza Gratis:")
            st.write(Lg.head())


        Lr = Lr.dropna(subset=['Pakiet']) 
        Lg = Lg.dropna(subset=['Pakiet']) 

        Lg = Lg[~Lg['Pakiet'].str.lower().str.contains('brak')]

        Lr = Lr.dropna(subset=['Klient'])
        # klient na całkowite
        Lr = Lr[Lr['Klient'] != '(puste)']
        Lg = Lg[Lg['Klient'] != '(puste)']

        Lr['Klient'] = Lr['Klient'].astype(int)
        Lg['Klient'] = Lg['Klient'].astype(int)
        Lg['Indeks'] = Lg['Indeks'].astype(int)



        Lr.columns=['Klient','Pakiet']
 
        
        # Dodaj kolumnę 'SIECIOWY', która będzie zawierać 'SIECIOWY' jeśli w kolumnach '12' lub '14' jest słowo 'powiązanie'
        Lr['SIECIOWY'] = Lr.apply(lambda row: 'SIECIOWY' if 'powiązanie' in str(row['Pakiet']).lower() else '', axis=1)
        

        Lr['Pakiet'] = Lr['Pakiet'].apply(extract_percentage)

        Lg['pakiet'] = Lg['Pakiet'].apply(extract_numbers_as_text)
        
        Lg['SIECIOWY'] = 'SIECIOWY'
        Lg

        # na zmiennoprzecinkowe
        Lr['Pakiet'] = Lr['Pakiet'].apply(percentage_to_float)
        Lr
    
        # TUTAJ DOPISZ TĘ LINIĘ – zostawiamy tylko pakiety równe 20% (0.20)
        Lr = Lr[Lr['Pakiet'] == 20]
    
        # Dodaj nową kolumnę 'max_percent'
        Lr1 = Lr[Lr['SIECIOWY'] == 'SIECIOWY']
        Lr2 = Lr[Lr['SIECIOWY'] != 'SIECIOWY']
        Lr1['max_percent'] = Lr1[['Pakiet']].max(axis=1)
        Lr2['max_percent'] = Lr2[['Pakiet']].max(axis=1)
        
        ###### 1 to SIECIOWI, 2 to punkt dostaw
        Lr1 = Lr1[['Klient','max_percent']]
        Lr2 = Lr2[['Klient','max_percent']]

        
        #### p
        Lg1 = Lg[['Klient','Indeks','pakiet']]

        stand_lr = Lr2.rename(columns={'Klient': 'Kod SAP'})
        pow_lr = Lr1

        pow_lg = Lg1
        pow_lg['Logiczne'] = pow_lg['Indeks'].astype(str) + '_' + pow_lg['pakiet'].astype(str)

        mapa_nielogiczne = {
            # --- ARKUSZ 1 ---
            '97520_60+15': '97520_4+1', '97520_4+1': '97520_4+1',
            '117226_80+26': '117226_8+3', '117226_8+3': '117226_8+3',
            '117790_80+26': '117790_8+3', '117790_8+3': '117790_8+3',
            '65601_80+30': '65601_8+3', '65601_8+3': '65601_8+3',
            '65602_80+30': '65602_8+3', '65602_8+3': '65602_8+3',
            '66660_80+30': '66660_8+3', '66660_8+3': '66660_8+3',
            '120002_50+10': '120002_5+1', '120002_5+1': '120002_5+1',

            # --- ARKUSZ 2 ---
            '122969_80+30': '122969_8+3', '122969_8+3': '122969_8+3',
            '97032_60+15': '97032_8+2', '97032_8+2': '97032_8+2',
            '121729_50+15': '121729_10+3', '121729_10+3': '121729_10+3',
            '121730_50+15': '121730_10+3', '121730_10+3': '121730_10+3',
            '97047_100+45': '97047_5+2', '97047_5+2': '97047_5+2',
            '97048_100+45': '97048_5+2', '97048_5+2': '97048_5+2',
            '97049_50+20': '97049_5+2', '97049_5+2': '97049_5+2',

            # --- ARKUSZ 3 ---
            '97050_100+45': '97050_5+2', '97050_5+2': '97050_5+2',
            '97051_100+45': '97051_5+2', '97051_5+2': '97051_5+2',
            '97052_50+20': '97052_5+2', '97052_5+2': '97052_5+2',
            '123542_50+20': '123542_5+2', '123542_5+2': '123542_5+2',
            '116878_50+20': '116878_5+2', '116878_5+2': '116878_5+2',
            '116929_50+20': '116929_5+2', '116929_5+2': '116929_5+2',
            '91580_80+30': '91580_8+3', '91580_8+3': '91580_8+3',

            # --- ARKUSZ 4 ---
            '91743_60+20': '91743_6+2', '91743_6+2': '91743_6+2',
            '110155_60+15': '110155_4+1', '110155_4+1': '110155_4+1',
            '97042_100+70': '97042_10+7', '97042_10+7': '97042_10+7',
            '97044_100+70': '97044_10+7', '97044_10+7': '97044_10+7',
            '97045_60+40': '97045_6+4', '97045_6+4': '97045_6+4',
            '69165_80+30': '69165_8+3', '69165_8+3': '69165_8+3',
            '75127_80+30': '75127_8+3', '75127_8+3': '75127_8+3',

            # --- ARKUSZ 5 ---
            '121724_60+20': '121724_6+2', '121724_6+2': '121724_6+2',
            '122696_60+20': '122696_6+2', '122696_6+2': '122696_6+2',
            '65007_40+10': '65007_4+1', '65007_4+1': '65007_4+1',
            '70144_80+30': '70144_8+3', '70144_8+3': '70144_8+3',
            '69133_80+30': '69133_8+3', '69133_8+3': '69133_8+3',
            '62472_80+30': '62472_8+3', '62472_8+3': '62472_8+3',
            '97686_80+30': '97686_8+3', '97686_8+3': '97686_8+3',

            # --- ARKUSZ 6 ---
            '84747_40+10': '84747_4+1', '84747_4+1': '84747_4+1',
            '66526_63+21': '66526_21+7', '66526_21+7': '66526_21+7',
            '114162_80+30': '114162_8+3', '114162_8+3': '114162_8+3',
            '81142_80+30': '81142_8+3', '81142_8+3': '81142_8+3',
            '77745_80+30': '77745_8+3', '77745_8+3': '77745_8+3',
            '89051_80+30': '89051_8+3', '89051_8+3': '89051_8+3',
            '103315_80+30': '103315_8+3', '103315_8+3': '103315_8+3',

            # --- ARKUSZ 7 ---
            '91367_80+30': '91367_8+3', '91367_8+3': '91367_8+3',
            '102152_80+30': '102152_8+3', '102152_8+3': '102152_8+3',
            '116405_80+30': '116405_8+3', '116405_8+3': '116405_8+3',
            '117222_50+15': '117222_10+3', '117222_10+3': '117222_10+3',
            '117223_50+15': '117223_10+3', '117223_10+3': '117223_10+3',
            '117225_50+15': '117225_10+3', '117225_10+3': '117225_10+3',
            '103687_50+15': '103687_10+3', '103687_10+3': '103687_10+3',

            # --- ARKUSZ 8 ---
            '117224_50+15': '117224_10+3', '117224_10+3': '117224_10+3',
            '103688_50+15': '103688_10+3', '103688_10+3': '103688_10+3',
            '97072_120+40': '97072_10+4', '97072_12+4': '97072_10+4',
            '97073_120+40': '97073_12+4', '97073_12+4': '97073_12+4',
            '76926_25+15': '76926_10+6', '76926_10+6': '76926_10+6'
        }
        
        # Zamiana wartości zgodnie z mapą (wiersze bez dopasowania dostaną NaN)
        pow_lg['Nielogiczne'] = pow_lg['Logiczne'].map(mapa_nielogiczne)

        # Usunięcie wierszy, które nie pasowały do mapy (czyli mają NaN)
        pow_lg = pow_lg.dropna(subset=['Nielogiczne'])
        
        # Wyświetlenie wyniku w aplikacji Streamlit
        st.write("Wiersze dopasowane i zmienione według mapy:")
        st.dataframe(pow_lg)

        
        #TERAZ IMS
        ims = st.file_uploader(
            label = "Wrzuć plik ims_nhd"
        )
    
        if ims:
            ims = pd.read_excel(ims, usecols=[0,2,19,21])
            st.write(ims.head())
    
        ims = ims[ims['APD_Czy_istnieje_na_rynku']==1]
        ims = ims[ims['APD_Rodzaj_farmaceutyczny'].isin(['AP - Apteka','ME - Sklep zielarsko - medyczny','PU - Punkt apteczny'])]
    
        wynik_df_lr = pd.merge(pow_lr, ims, left_on='Klient', right_on='Klient', how='left')
        
        wynik_df_lg = pd.merge(pow_lg, ims, left_on='Klient', right_on='Klient', how='left')
    
        # Wybór potrzebnych kolumn: 'APD_kod_SAP_apteki' i 'max_percent'
        wynik_df_lr = wynik_df_lr[['Klient','APD_kod_SAP_apteki', 'max_percent']]
        wynik_df_lg = wynik_df_lg[['Klient','APD_kod_SAP_apteki', 'Indeks', 'Nielogiczne']]
    
        #to są kody SAP
        wynik_df1_lr = wynik_df_lr.rename(columns={'APD_kod_SAP_apteki': 'Kod SAP'})
        wynik_df1_lr = wynik_df1_lr[['Kod SAP','max_percent']]

        wynik_df1_lg = wynik_df_lg.rename(columns={'APD_kod_SAP_apteki': 'Kod SAP'})
        wynik_df1_lg = wynik_df1_lg[['Kod SAP','Indeks','Nielogiczne']]

        #wynik_df1
    
        #to są kody powiazan
        wynik_df2_lr = wynik_df_lr.rename(columns={'Klient': 'Kod SAP'})
        wynik_df2_lr = wynik_df2_lr[['Kod SAP','max_percent']]

        wynik_df2_lg = wynik_df_lg.rename(columns={'Klient': 'Kod SAP'})
        wynik_df2_lg = wynik_df2_lg[['Kod SAP','Indeks','Nielogiczne']]

        #wynik_df2

        #POŁĄCZYĆ wynik_df z standard_ost
        polaczone_lr = pd.concat([stand_lr, wynik_df1_lr, wynik_df2_lr], axis = 0)

        polaczone_lg = pd.concat([wynik_df1_lg, wynik_df2_lg], axis = 0)
  
        posortowane_lr = polaczone_lr.sort_values(by='max_percent', ascending=False)

        ostatecznie_lr = posortowane_lr.drop_duplicates(subset='Kod SAP')
        ostatecznie_lr = ostatecznie_lr[ostatecznie_lr['max_percent'] != 0]


        ostatecznie_lg = polaczone_lg.drop_duplicates(subset=['Kod SAP', 'Indeks', 'Nielogiczne'])

        # Grupy zdefiniowane na podstawie przesłanego obrazka (arkusz 1 do arkusz 8)
        grupa_1 = [97520, 117226, 117790, 65601, 65602, 66660, 120002]
        grupa_2 = [122969, 97032, 121729, 121730, 97047, 97048, 97049]
        grupa_3 = [97050, 97051, 97052, 123542, 116878, 116929, 91580]
        grupa_4 = [91743, 110155, 97042, 97044, 97045, 69165, 75127]
        grupa_5 = [121724, 122696, 65007, 70144, 69133, 62472, 97686]
        grupa_6 = [84747, 66526, 114162, 81142, 77745, 89051, 103315]
        grupa_7 = [91367, 102152, 116405, 117222, 117223, 117225, 103687]
        grupa_8 = [117224, 103688, 97072, 97073, 76926]

        arkusze_gratis = {
            'arkusz 1': ostatecznie_lg[ostatecznie_lg['Indeks'].isin(grupa_1)],
            'arkusz 2': ostatecznie_lg[ostatecznie_lg['Indeks'].isin(grupa_2)],
            'arkusz 3': ostatecznie_lg[ostatecznie_lg['Indeks'].isin(grupa_3)],
            'arkusz 4': ostatecznie_lg[ostatecznie_lg['Indeks'].isin(grupa_4)],
            'arkusz 5': ostatecznie_lg[ostatecznie_lg['Indeks'].isin(grupa_5)],
            'arkusz 6': ostatecznie_lg[ostatecznie_lg['Indeks'].isin(grupa_6)],
            'arkusz 7': ostatecznie_lg[ostatecznie_lg['Indeks'].isin(grupa_7)],
            'arkusz 8': ostatecznie_lg[ostatecznie_lg['Indeks'].isin(grupa_8)],
        }

        st.write('Jeśli to pierwszy monitoring, pobierz ten plik, jeśli nie, wrzuć plik z poprzedniego monitoringu i NIE POBIERAJ TEGO PLIKU')
        excel_file = io.BytesIO()
        
        with pd.ExcelWriter(excel_file, engine='xlsxwriter') as writer:
        
            # arkusz bez zmian
            if 'ostatecznie_lr' in locals():
                ostatecznie_lr.to_excel(writer, index=False, sheet_name='Rabat')
        
            # grupy LG w osobnych arkuszach (od 1 do 8)
            for nazwa_arkusza, df_grupy in arkusze_gratis.items():
                if not df_grupy.empty:
                    df_grupy.to_excel(writer, index=False, sheet_name=nazwa_arkusza)


        excel_file.seek(0)  # Resetowanie wskaźnika do początku pliku

         # Umożliwienie pobrania pliku Excel
        st.download_button(
            label='Pobierz, jeśli to pierwszy monitoring',
            data=excel_file,
            file_name='czy_dodac.xlsx',
            mime='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
        )

        # Plik z poprzedniego monitoringu 
        poprzedni = st.file_uploader(label="Wrzuć plik z poprzedniego monitoringu")
    
        # Plik z poprzedniego monitoringu
        if poprzedni:
            xls = pd.ExcelFile(poprzedni)
        
        # Rabat – bez zmian
        if 'Rabat' in xls.sheet_names:
            poprzedni_lr = pd.read_excel(poprzedni, sheet_name='Rabat')
            st.write('Poprzedni monitoring - Rabat:')
            st.write(poprzedni_lr.head())
        
        # Gratis – 8 grup
        poprzedni_gratis = {}
        
        for nazwa in arkusze_gratis.keys():
            if nazwa in xls.sheet_names:
                poprzedni_gratis[nazwa] = pd.read_excel(poprzedni, sheet_name=nazwa)
                st.write(f'Poprzedni monitoring - {nazwa}:')
                st.write(poprzedni_gratis[nazwa].head())


        if 'ostatecznie_lr' in locals() and 'poprzedni_lr' in locals():
            poprzedni_lr = poprzedni_lr.rename(columns={'max_percent': 'old_percent'})
            
            ostatecznie_lr['Kod SAP'] = ostatecznie_lr['Kod SAP'].astype(str).str.strip()
            poprzedni_lr['Kod SAP'] = poprzedni_lr['Kod SAP'].astype(str).str.strip()
            
            result_lr = ostatecznie_lr.merge(
                poprzedni_lr[['Kod SAP', 'old_percent']],
                on='Kod SAP',
                how='left'
            )
            result_lr['old_percent'] = result_lr['old_percent'].fillna(0)
            result_lr['Czy dodać'] = result_lr.apply(
                lambda row: 'DODAJ' if row['max_percent'] > row['old_percent'] else '',
                axis=1
            )

        wyniki_gratis = {}
        
        for nazwa, df_aktualny in arkusze_gratis.items():
        
            df_poprzedni = poprzedni_gratis.get(nazwa)
        
            if df_poprzedni is not None:
                result = pd.concat([df_aktualny, df_poprzedni], ignore_index=True)
        
                result = result.drop_duplicates(
                    subset=['Kod SAP', 'Indeks','Nielogiczne'],
                    keep='first'
                )
        
                result['Czy dodać'] = result.apply(
                    lambda row: 'DODAJ'
                    if not (
                        (row['Kod SAP'] in df_poprzedni['Kod SAP'].values)
                        and (row['Nielogiczne'] in df_poprzedni['Nielogiczne'].values)
                    )
                    else '',
                    axis=1
                )
            else:
                result = df_aktualny.copy()
                result['Czy dodać'] = 'DODAJ'
        
            wyniki_gratis[nazwa] = result


        excel_file1 = io.BytesIO()
        
        with pd.ExcelWriter(excel_file1, engine='xlsxwriter') as writer:
        
            if 'result_lr' in locals():
                result_lr.to_excel(writer, index=False, sheet_name='Rabat')
        
            for nazwa, df in wyniki_gratis.items():
                df.to_excel(writer, index=False, sheet_name=nazwa)

        excel_file1.seek(0)  # Resetowanie wskaźnika do początku pliku

        # Definiowanie nazwy pliku
        nazwa_pliku = f"ZIMÓWKA_{dzisiejsza_data}.xlsx"
        # Umożliwienie pobrania pliku Excel
        st.download_button(
            label='Kliknij aby pobrać plik z kodami, które kody należy dodać',
            data=excel_file1,
            file_name=nazwa_pliku,
            mime='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
        )



        # Rabat – bez zmian
        result_lr = result_lr.drop(columns=['old_percent', 'Czy dodać'], errors='ignore')
        
        # Gratis – każda grupa osobno
        for nazwa in wyniki_gratis:
            wyniki_gratis[nazwa] = wyniki_gratis[nazwa].drop(
                columns=['Czy dodać'],
                errors='ignore'
            )


        st.write('Kliknij, aby pobrać plik z formułą max do następnego monitoringu')


        excel_file2 = io.BytesIO()

        with pd.ExcelWriter(excel_file2, engine='xlsxwriter') as writer:
        
            # Rabat
            result_lr.to_excel(writer, index=False, sheet_name='Rabat')
        
            # Gratis – 8 arkuszy
            for nazwa, df in wyniki_gratis.items():
                df.to_excel(writer, index=False, sheet_name=nazwa)


        excel_file2.seek(0)
        
        nazwa_pliku = f"FM_ZIMÓWKA_{dzisiejsza_data}.xlsx"
        
        st.download_button(
            label='Pobierz nowy plik FORMUŁA MAX',
            data=excel_file2,
            file_name=nazwa_pliku,
            mime='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
        )




############################################################################### VIT D ##############################################################################################
if sekcja == 'Vit D':
    st.write(tabs_font_css, unsafe_allow_html=True)

    df = st.file_uploader(label="Wrzuć plik - Vit D")
    
    if df:
        xls = pd.ExcelFile(df)

        # 1. Odczyt arkuszy
        Lr = pd.DataFrame()
        Lg = pd.DataFrame()

        if 'Rabat' in xls.sheet_names:
            Lr = pd.read_excel(df, sheet_name='Rabat', skiprows=12, usecols=[1, 6])
            st.write("Dane z arkusza Rabat:")
            st.write(Lr.head())

        if 'Pakiet od 02.07' in xls.sheet_names:
            Lg = pd.read_excel(df, sheet_name='Pakiet od 02.07', skiprows=7, usecols=[1, 6])
            st.write("Dane z arkusza Pakiet od 02.07:")
            st.write(Lg.head())

        # --- CZYSZCZENIE I PRZYGOTOWANIE DANYCH ---
        if not Lr.empty:
            Lr.columns = ['Klient', 'Pakiet']
            Lr = Lr.dropna(subset=['Pakiet', 'Klient'])
            Lr = Lr[Lr['Klient'] != '(puste)']
            Lr['Klient'] = Lr['Klient'].astype(int)

            # Identyfikacja sieciowych
            Lr['SIECIOWY'] = Lr.apply(lambda row: 'SIECIOWY' if 'powiązanie' in str(row['Pakiet']).lower() else '', axis=1)
            
            # Ekstrakcja i konwersja wartości procentowych
            Lr['Pakiet'] = Lr['Pakiet'].apply(extract_percentage)
            Lr['Pakiet'] = Lr['Pakiet'].apply(percentage_to_float)
            
            # Zostawiamy rabaty równe lub większe od 20%
            Lr = Lr[Lr['Pakiet'] >= 20]

            # Dynamiczne generowanie grupy promocyjnej
            Lr['Grupa promocyjna'] = Lr['Pakiet'].apply(lambda x: f"VIT_D3_MAX_{int(x)}")

            # Wyznaczenie max_percent dla sieciowych i indywidualnych
            Lr1 = Lr[Lr['SIECIOWY'] == 'SIECIOWY'].copy()
            Lr2 = Lr[Lr['SIECIOWY'] != 'SIECIOWY'].copy()
            Lr1['max_percent'] = Lr1['Pakiet']
            Lr2['max_percent'] = Lr2['Pakiet']

            pow_lr = Lr1[['Klient', 'max_percent', 'Grupa promocyjna']]
            stand_lr = Lr2[['Klient', 'max_percent', 'Grupa promocyjna']].rename(columns={'Klient': 'Kod SAP'})

        if not Lg.empty:
            Lg.columns = ['Klient', 'Pakiet']
            Lg = Lg.dropna(subset=['Pakiet', 'Klient'])
            Lg = Lg[~Lg['Pakiet'].str.lower().str.contains('brak')]
            Lg = Lg[Lg['Klient'] != '(puste)']
            Lg['Klient'] = Lg['Klient'].astype(int)

            Lg['pakiet'] = Lg['Pakiet'].apply(extract_numbers_as_text)
            
            # Mapowanie pakietów na format 'Rodzaj pakietu'
            mapa_rodzaj_pakietu = {
                '10+4': '10+4',
                '50+21': '50+21',
                '100+45': '20+9'
            }
            
            pow_lg = Lg[['Klient', 'pakiet']].copy()
            pow_lg['Rodzaj pakietu'] = pow_lg['pakiet'].map(mapa_rodzaj_pakietu)
            pow_lg = pow_lg.dropna(subset=['Rodzaj pakietu'])

            # Rozbijanie na wiersze z odpowiednimi Grupami Promocyjnymi
            rekordy_lg = []
            for _, row in pow_lg.iterrows():
                rodzaj_val = row['Rodzaj pakietu']
                klient_val = row['Klient']

                if rodzaj_val == '50+21':
                    # Dodajemy dwa wiersze dla pakietu 50+21
                    rekordy_lg.append({'Klient': klient_val, 'Rodzaj pakietu': rodzaj_val, 'Grupa promocyjna': 'VITD3M60_50+21'})
                    rekordy_lg.append({'Klient': klient_val, 'Rodzaj pakietu': rodzaj_val, 'Grupa promocyjna': 'VITD3M60_10+4'})
                elif rodzaj_val == '10+4':
                    rekordy_lg.append({'Klient': klient_val, 'Rodzaj pakietu': rodzaj_val, 'Grupa promocyjna': 'VITD3M60_10+4'})
                elif rodzaj_val == '20+9':
                    rekordy_lg.append({'Klient': klient_val, 'Rodzaj pakietu': rodzaj_val, 'Grupa promocyjna': 'VITD3M60_20+9'})

            pow_lg = pd.DataFrame(rekordy_lg)

            st.write("Wiersze dopasowane i zmienione według mapy (Pakiet od 02.07):")
            st.dataframe(pow_lg)

        # --- OBSŁUGA PLIKU IMS ---
        ims = st.file_uploader(label="Wrzuć plik ims_nhd")
        
        if ims:
            ims = pd.read_excel(ims, usecols=[0, 2, 19, 21])
            ims = ims[ims['APD_Czy_istnieje_na_rynku'] == 1]
            ims = ims[ims['APD_Rodzaj_farmaceutyczny'].isin(['AP - Apteka', 'ME - Sklep zielarsko - medyczny', 'PU - Punkt apteczny'])]

            # --- ŁĄCZENIE LR (RABAT) ---
            if 'pow_lr' in locals() and not pow_lr.empty:
                wynik_df_lr = pd.merge(pow_lr, ims, left_on='Klient', right_on='Klient', how='left')
                wynik_df1_lr = wynik_df_lr[['APD_kod_SAP_apteki', 'max_percent', 'Grupa promocyjna']].rename(columns={'APD_kod_SAP_apteki': 'Kod SAP'})
                wynik_df2_lr = wynik_df_lr[['Klient', 'max_percent', 'Grupa promocyjna']].rename(columns={'Klient': 'Kod SAP'})
                
                polaczone_lr = pd.concat([stand_lr, wynik_df1_lr, wynik_df2_lr], axis=0)
                posortowane_lr = polaczone_lr.sort_values(by='max_percent', ascending=False)
                ostatecznie_lr = posortowane_lr.drop_duplicates(subset=['Kod SAP', 'Grupa promocyjna'])
                ostatecznie_lr = ostatecznie_lr[ostatecznie_lr['max_percent'] != 0]

            # --- ŁĄCZENIE LG (PAKIET OD 02.07) ---
            if 'pow_lg' in locals() and not pow_lg.empty:
                wynik_df_lg = pd.merge(pow_lg, ims, left_on='Klient', right_on='Klient', how='left')
                wynik_df1_lg = wynik_df_lg[['APD_kod_SAP_apteki', 'Rodzaj pakietu', 'Grupa promocyjna']].rename(columns={'APD_kod_SAP_apteki': 'Kod SAP'})
                wynik_df2_lg = wynik_df_lg[['Klient', 'Rodzaj pakietu', 'Grupa promocyjna']].rename(columns={'Klient': 'Kod SAP'})
                
                polaczone_lg = pd.concat([wynik_df1_lg, wynik_df2_lg], axis=0)
                ostatecznie_lg = polaczone_lg.dropna(subset=['Kod SAP']).drop_duplicates(subset=['Kod SAP', 'Rodzaj pakietu', 'Grupa promocyjna'])

            # --- PIERWSZY MONITORING: GENEROWANIE PLIKU ---
            st.write('Jeśli to pierwszy monitoring, pobierz ten plik. Jeśli nie, wrzuć plik z poprzedniego monitoringu poniżej.')
            excel_file = io.BytesIO()
            
            with pd.ExcelWriter(excel_file, engine='xlsxwriter') as writer:
                if 'ostatecznie_lr' in locals() and not ostatecznie_lr.empty:
                    ostatecznie_lr.to_excel(writer, index=False, sheet_name='Rabat')
                if 'ostatecznie_lg' in locals() and not ostatecznie_lg.empty:
                    ostatecznie_lg.to_excel(writer, index=False, sheet_name='Pakiet od 02.07')

            excel_file.seek(0)
            st.download_button(
                label='Pobierz, jeśli to pierwszy monitoring',
                data=excel_file,
                file_name='czy_dodac.xlsx',
                mime='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
            )

            # --- PORÓWNANIE Z POPRZEDNIM MONITORINGIEM ---
            poprzedni = st.file_uploader(label="Wrzuć plik z poprzedniego monitoringu")
            
            if poprzedni:
                xls_pop = pd.ExcelFile(poprzedni)
                
                # Porównanie Rabat
                if 'Rabat' in xls_pop.sheet_names and 'ostatecznie_lr' in locals():
                    poprzedni_lr = pd.read_excel(poprzedni, sheet_name='Rabat')
                    poprzedni_lr = poprzedni_lr.rename(columns={'max_percent': 'old_percent'})
                    
                    ostatecznie_lr['Kod SAP'] = ostatecznie_lr['Kod SAP'].astype(str).str.strip()
                    poprzedni_lr['Kod SAP'] = poprzedni_lr['Kod SAP'].astype(str).str.strip()
                    
                    result_lr = ostatecznie_lr.merge(
                        poprzedni_lr[['Kod SAP', 'Grupa promocyjna', 'old_percent']],
                        on=['Kod SAP', 'Grupa promocyjna'],
                        how='left'
                    )
                    result_lr['old_percent'] = result_lr['old_percent'].fillna(0)
                    result_lr['Czy dodać'] = result_lr.apply(
                        lambda row: 'DODAJ' if row['max_percent'] > row['old_percent'] else '',
                        axis=1
                    )
                else:
                    result_lr = ostatecznie_lr.copy() if 'ostatecznie_lr' in locals() else pd.DataFrame()
                    if not result_lr.empty:
                        result_lr['Czy dodać'] = 'DODAJ'

                # Porównanie Pakiet od 02.07
                if 'Pakiet od 02.07' in xls_pop.sheet_names and 'ostatecznie_lg' in locals():
                    poprzedni_lg = pd.read_excel(poprzedni, sheet_name='Pakiet od 02.07')
                    
                    # Obsługa potencjalnej wstecznej kompatybilności, gdyby w starym pliku była jeszcze nazwa 'Nielogiczne'
                    if 'Nielogiczne' in poprzedni_lg.columns and 'Rodzaj pakietu' not in poprzedni_lg.columns:
                        poprzedni_lg = poprzedni_lg.rename(columns={'Nielogiczne': 'Rodzaj pakietu'})

                    poprzedni_lg['Kod SAP'] = poprzedni_lg['Kod SAP'].astype(str).str.strip()
                    ostatecznie_lg['Kod SAP'] = ostatecznie_lg['Kod SAP'].astype(str).str.strip()

                    result_lg = pd.concat([ostatecznie_lg, poprzedni_lg], ignore_index=True)
                    result_lg = result_lg.drop_duplicates(subset=['Kod SAP', 'Rodzaj pakietu', 'Grupa promocyjna'], keep='first')
                    
                    pary_poprzednie = set(zip(poprzedni_lg['Kod SAP'], poprzedni_lg['Rodzaj pakietu'], poprzedni_lg['Grupa promocyjna']))
                    result_lg['Czy dodać'] = result_lg.apply(
                        lambda row: '' if (row['Kod SAP'], row['Rodzaj pakietu'], row['Grupa promocyjna']) in pary_poprzednie else 'DODAJ',
                        axis=1
                    )
                else:
                    result_lg = ostatecznie_lg.copy() if 'ostatecznie_lg' in locals() else pd.DataFrame()
                    if not result_lg.empty:
                        result_lg['Czy dodać'] = 'DODAJ'

                # --- EXPORT PLIKU Z "CZY DODAĆ" ---
                excel_file1 = io.BytesIO()
                with pd.ExcelWriter(excel_file1, engine='xlsxwriter') as writer:
                    if 'result_lr' in locals() and not result_lr.empty:
                        result_lr.to_excel(writer, index=False, sheet_name='Rabat')
                    if 'result_lg' in locals() and not result_lg.empty:
                        result_lg.to_excel(writer, index=False, sheet_name='Pakiet od 02.07')

                excel_file1.seek(0)
                nazwa_pliku = f"VIT_D_{dzisiejsza_data}.xlsx"
                st.download_button(
                    label='Kliknij aby pobrać plik z kodami, które kody należy dodać',
                    data=excel_file1,
                    file_name=nazwa_pliku,
                    mime='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
                )

                # --- EXPORT PLIKU "FORMUŁA MAX" (DO NASTĘPNEGO MONITORINGU) ---
                if 'result_lr' in locals() and not result_lr.empty:
                    result_lr_fm = result_lr.drop(columns=['old_percent', 'Czy dodać'], errors='ignore')
                else:
                    result_lr_fm = pd.DataFrame()

                if 'result_lg' in locals() and not result_lg.empty:
                    result_lg_fm = result_lg.drop(columns=['Czy dodać'], errors='ignore')
                else:
                    result_lg_fm = pd.DataFrame()

                excel_file2 = io.BytesIO()
                with pd.ExcelWriter(excel_file2, engine='xlsxwriter') as writer:
                    if not result_lr_fm.empty:
                        result_lr_fm.to_excel(writer, index=False, sheet_name='Rabat')
                    if not result_lg_fm.empty:
                        result_lg_fm.to_excel(writer, index=False, sheet_name='Pakiet od 02.07')

                excel_file2.seek(0)
                nazwa_pliku_fm = f"FM_VIT_D_{dzisiejsza_data}.xlsx"
                st.download_button(
                    label='Pobierz nowy plik FORMUŁA MAX',
                    data=excel_file2,
                    file_name=nazwa_pliku_fm,
                    mime='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
                )




        






    
    







        


















    
